PR#5199: tests are run only for bytecode if either native support is missing, or a non-empty value is set to "BYTECODE_ONLY" Makefile variable.
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@12041 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -16,12 +16,14 @@ run-byte: common
 	@echo " => passed"
 
 run-opt: common
-	@printf " ... testing 'native':"
-	@$(OCAMLOPT) -c tcallback.ml
-	@$(OCAMLOPT) -o ./program unix.cmxa callbackprim.$(O) tcallback.cmx
-	@./program > native.result
-	@$(DIFF) reference native.result || (echo " => failed" && exit 1) 
-	@echo " => passed"
+	@if [ -z "$(BYTECODE_ONLY)" ]; then \
+	  printf " ... testing 'native':"; \
+	  $(OCAMLOPT) -c tcallback.ml; \
+	  $(OCAMLOPT) -o ./program unix.cmxa callbackprim.$(O) tcallback.cmx; \
+	  ./program > native.result; \
+	  $(DIFF) reference native.result || (echo " => failed" && exit 1); \
+	  echo " => passed"; \
+	fi
 	
 promote: defaultpromote
 
diff --git a/testsuite/tests/runtime-errors/Makefile b/testsuite/tests/runtime-errors/Makefile
--- a/testsuite/tests/runtime-errors/Makefile
+++ b/testsuite/tests/runtime-errors/Makefile
@@ -5,10 +5,10 @@ default: compile run
 compile:
 	@for f in *.ml; do \
 	  $(OCAMLC) -w a -o `basename $$f ml`bytecode $$f; \
-	  $(OCAMLOPT) -w a -o `basename $$f ml`native $$f; \
+	  test -z "$(BYTECODE_ONLY)" && $(OCAMLOPT) -w a -o `basename $$f ml`native $$f || true; \
 	done
 	@if [ ! `grep -c HAS_STACK_OVERFLOW_DETECTION ../../../config/s.h` ]; then \
-	  rm -f stackoverflow.byte stackoverflow.native; \
+	  test -z "$(BYTECODE_ONLY)" && rm -f stackoverflow.byte stackoverflow.native || true; \
 	fi
 
 run:
@@ -17,11 +17,13 @@ run:
 	  printf " ... testing '$$f':"; \
 	  (./$$f > $$f.result 2>&1; true); \
 	  $(DIFF) $$f.reference $$f.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
-	  printf " ... testing '`basename $$f bytecode`native':"; \
-	  (./`basename $$f bytecode`native > `basename $$f bytecode`native.result 2>&1; true); \
-	  $(DIFF) `basename $$f bytecode`native.reference `basename $$f bytecode`native.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
+	  if [ -z "$(BYTECODE_ONLY)" ]; then \
+	    printf " ... testing '`basename $$f bytecode`native':"; \
+	    (./`basename $$f bytecode`native > `basename $$f bytecode`native.result 2>&1; true); \
+	    $(DIFF) `basename $$f bytecode`native.reference `basename $$f bytecode`native.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
+	  fi; \
 	done
-	
+
 promote: defaultpromote
 
 clean: defaultclean
