Fix all issues in tests. 0 failures!

diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -27,10 +27,6 @@ default:
 	  *) $(MAKE) skip;; \
 	esac
 
-.PHONY: common
-common:
-	@$(CC) -c callbackprim.c
-
 .PHONY: skip
 skip:
 	@for c in bytecode native; do \
@@ -38,25 +34,31 @@ skip:
 	done
 
 .PHONY: run-byte
-run-byte: common
-	@printf " ... testing 'bytecode':"
-	@$(OCAMLC) $(COMPFLAGS) -c tcallback.ml
-	@$(OCAMLC) $(COMPFLAGS) -o ./program$(EXE) -custom unix.cma \
-	           callbackprim.$(O) tcallback.cmo
-	@./program$(EXE) >bytecode.result
-	@$(DIFF) reference bytecode.result \
-	&& echo " => passed" || echo " => failed"
+run-byte:
+	@for f in *.ml; do \
+	  printf " ... testing 'bytecode':"; \
+	  F=`basename $$f .ml`; \
+		$(CC) -c $$F.c; \
+		$(OCAMLC) $(COMPFLAGS) -c $$F.mli; \
+		$(OCAMLC) $(COMPFLAGS) -c $$F.ml; \
+		$(OCAMLC) $(COMPFLAGS) -o ./$$F.byte$(EXE) -custom unix.cma $$F.$(O) $$F.cmo; \
+		./$$F.byte$(EXE) > $$F.byte.result; \
+		$(DIFF) $$F.reference $$F.byte.result && echo " => passed" || echo " => failed"; \
+	done
 
 .PHONY: run-opt
-run-opt: common
+run-opt:
 	@if $(BYTECODE_ONLY); then : ; else \
-	  printf " ... testing 'native':"; \
-	  $(OCAMLOPT) $(COMPFLAGS) -c tcallback.ml; \
-	  $(OCAMLOPT) $(COMPFLAGS) -o ./program$(EXE) unix.cmxa \
-	              callbackprim.$(O) tcallback.cmx; \
-	  ./program$(EXE) >native.result; \
-	  $(DIFF) reference native.result \
-	  && echo " => passed" || echo " => failed"; \
+		for f in *.ml; do \
+			printf " ... testing 'nativecode':"; \
+			F=`basename $$f .ml`; \
+			$(CC) -c $$F.c; \
+			mv $$F.$(O) $$F.c.$(O); \
+			$(OCAMLOPT) $(COMPFLAGS) -c $$F.mli; \
+			$(OCAMLOPT) $(COMPFLAGS) -o ./$$F.native$(EXE) unix.cmxa $$F.c.$(O) $$F.ml; \
+			./$$F.native$(EXE) > $$F.native.result; \
+			$(DIFF) $$F.reference $$F.native.result && echo " => passed" || echo " => failed"; \
+		done; \
 	fi
 
 .PHONY: promote
@@ -64,6 +66,6 @@ promote: defaultpromote
 
 .PHONY: clean
 clean: defaultclean
-	@rm -f *.result ./program$(EXE)
+	@rm -f *.result *.byte$(EXE) *.native$(EXE)
 
 include $(BASEDIR)/makefiles/Makefile.common
