fix TABs and whitespace
git-svn-id: http://caml.inria.fr/svn/ocaml/version/4.00@12800 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -12,7 +12,7 @@ run-byte: common
 	@$(OCAMLC) -c tcallback.ml
 	@$(OCAMLC) -o ./program -custom unix.cma callbackprim.$(O) tcallback.cmo
 	@./program > bytecode.result
-	@$(DIFF) reference bytecode.result || (echo " => failed" && exit 1) 
+	@$(DIFF) reference bytecode.result || (echo " => failed" && exit 1)
 	@echo " => passed"
 
 run-opt: common
@@ -24,7 +24,7 @@ run-opt: common
 	  $(DIFF) reference native.result || (echo " => failed" && exit 1); \
 	  echo " => passed"; \
 	fi
-	
+
 promote: defaultpromote
 
 clean: defaultclean
