Change references to `objinfo` to `ocamlobjinfo`
Address review comments and clean up quoting

Fix inconsistent makefile quoting and testsuite bustage

Fix includes of makefiles

Fix configure bug

make travis rerun

Trying to debug travis issue

Try to fix configure on Travis

Add config.mk which I had previously forgotten

to commit.

Fix silly makefile bug

Fix bug causing STUBLIBDIR to be empty

Fix makefile quoting bugs

Fix MSVC build break

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,7 +18,17 @@
 ocamlversion=`head -1 VERSION`
 echo "Configuring OCaml version $ocamlversion"
 
-configure_options="$*"
+awk_script='BEGIN {
+   for (i in ARGV) {
+       if (i > 0) {
+          gsub(i, /'\''/, "'\''\\\\'\&\''")
+          printf " '\'%s\''", ARGV[i]
+          delete ARGV[i]
+       }
+   }
+}'
+
+configure_options="$(awk -- "$awk_script" "$@" </dev/null)" || exit 1
 prefix=/usr/local
 bindir=''
 target_bindir=''
@@ -89,6 +99,52 @@ err() {
   exit 2
 }
 
+internal_error() {
+  printf "[INTERNAL ERROR (this is a bug)] %b\n" "$*" 1>&2
+  exit 4
+}
+
+emit_variable_internal () {
+  test "$2" -eq 1 ||
+    internal_error 'Bad number of arguments for emit_variable()'
+  varname=${1%%=*}
+  value=${1#*=}
+  case $varname in
+    *[!A-Za-z0-9_-]*)
+       internal_error "Invalid name passed to emit_variable(): ${varname}";;
+  esac
+}
+
+emit_variable() {
+  emit_variable_internal "$1" "$#"
+  case $value in
+    *["\$'
+"]*) printf 'define %s :=\n"' "$varname"
+     printf "%s" "$value" |
+       sed -e 's/["$\\`]/\\&/g' -e 's/\$/$$/g' -e 's/^/$(EMPTY)/'
+     printf '"\n\nendef\n';;
+    *) printf "%s := '%s'\\n" "$varname" "$value";;
+  esac
+}
+
+emit_variable_unquoted() {
+  emit_variable_internal "$1" "$#"
+  case ${1#*=} in
+    *['$
+']*) printf 'define %s :=\n' "$varname"
+     printf "%s" "$value" |
+       sed -e 's/\$/$$/g' -e 's/^/$(EMPTY)/'
+     printf '\n\nendef\n';;
+    *) printf "%s := %s\\n" "$varname" "$value";;
+  esac
+}
+
+unset CDPATH
+case $0 in
+    -*/*) cd "./${0%/*}";;
+    */*) cd "${0%/*}///";;
+    *) :;;
+esac || err "chdir failed!"
 exec 3>&1
 
 # Parse command-line arguments
@@ -179,26 +235,26 @@ done
 
 # Sanity checks
 
-case "$prefix" in
+case $prefix in
   /*) ;;
    *) err "The -prefix directory must be absolute.";;
 esac
-case "$bindir" in
+case $bindir in
   /*) ;;
   "") ;;
-  '$(PREFIX)/'*) ;;
+  '$(PREFIX)/'*) bindir=$prefix/${bindir#'$(PREFIX)/'};;
    *) err 'The -bindir directory must be absolute or relative to $(PREFIX).';;
 esac
-case "$libdir" in
+case $libdir in
   /*) ;;
   "") ;;
-  '$(PREFIX)/'*) ;;
+  '$(PREFIX)/'*) libdir=$prefix/${libdir#'$(PREFIX)/'};;
    *) err 'The -libdir directory must be absolute or relative to $(PREFIX).';;
 esac
-case "$mandir" in
+case $mandir in
   /*) ;;
   "") ;;
-  '$(PREFIX)/'*) ;;
+  '$(PREFIX)/'*) mandir=$prefix/${mandir#'$(PREFIX)/'};;
    *) err 'The -mandir directory must be absolute or relative to $(PREFIX).';;
 esac
 
@@ -206,32 +262,43 @@ esac
 
 cd config/auto-aux
 rm -f s.h m.h Makefile
-touch s.h m.h Makefile
+touch s.h m.h
+
+makefile=4
+
+exec 4>Makefile
 
 # Write options to Makefile
+printf %s\\n "# generated by ./configure$configure_options" |
+    sed 's/$/\\/
+$ s|\\$|\
+# ifeq ($(flavor EMPTY),undefined)\
+# $(error Include $$(TOPDIR)/global.mk instead of $$(TOPDIR)/config/Makefile)\
+# endif\
+override EMPTY :=|
+' >&4
 
-echo "# generated by ./configure $configure_options" >> Makefile
+emit_variable_unquoted "CONFIGURE_ARGS=$configure_options" >&$makefile
 
 # Where to install
 
-echo "PREFIX=$prefix" >> Makefile
-case "$bindir" in
-  "") echo 'BINDIR=$(PREFIX)/bin' >> Makefile
+emit_variable  "PREFIX=$prefix" >&$makefile
+case $bindir in
+  "") echo 'BINDIR:=$(PREFIX)/bin' >&$makefile
       bindir="$prefix/bin";;
-   *) echo "BINDIR=$bindir" >> Makefile;;
+   *) emit_variable "BINDIR=$bindir" >&$makefile;;
 esac
-case "$libdir" in
-  "") echo 'LIBDIR=$(PREFIX)/lib/ocaml' >> Makefile
+case $libdir in
+  "") echo 'LIBDIR:=$(PREFIX)/lib/ocaml' >&$makefile
       libdir="$prefix/lib/ocaml";;
-   *) echo "LIBDIR=$libdir" >> Makefile;;
+   *) emit_variable "LIBDIR=$libdir" >&$makefile;;
 esac
-echo 'STUBLIBDIR=$(LIBDIR)/stublibs' >> Makefile
-case "$mandir" in
-  "") echo 'MANDIR=$(PREFIX)/man' >> Makefile
+case $mandir in
+  "") echo 'MANDIR:=$(PREFIX)/man' >&$makefile
       mandir="$prefix/man";;
-   *) echo "MANDIR=$mandir" >> Makefile;;
+   *) emit_variable "MANDIR=$mandir" >&$makefile;;
 esac
-echo "MANEXT=$manext" >> Makefile
+emit_variable "MANEXT=$manext" >&$makefile
 
 # Determine the system type
 
@@ -240,7 +307,7 @@ if test "$host_type" = "unknown"; then
     err "Cannot guess host type. You must specify one with the -host option."
   fi
 fi
-if host=`../gnu/config.sub $host_type`; then :; else
+if host=`../gnu/config.sub "$host_type"`; then :; else
   err "Please specify the correct host type with the -host option"
 fi
 inf "Configuring for host $host ..."
@@ -394,7 +461,7 @@ case "$bytecc,$target" in
     dllccompopts="-U_WIN32 -DCAML_DLL"
     if test $with_sharedlibs = yes; then
       flexlink="flexlink -chain $flavor -merge-manifest -stack 16777216"
-      flexdir=`$flexlink -where | tr -d '\015'`
+      flexdir=`"$flexlink" -where | tr -d '\015'`
       if test -z "$flexdir"; then
         wrn "flexlink not found: native shared libraries won't be available."
         with_sharedlibs=no
@@ -481,7 +548,7 @@ if $cross_compiler; then
           "($ocaml_system_version) doesn't match the version of these\n" \
           "sources ($ocaml_source_version)."
     else
-      echo "CAMLRUN=`./searchpath -p ocamlrun`" >> Makefile
+      echo "CAMLRUN=`./searchpath -p ocamlrun`" >&$makefile
     fi
   fi
 
@@ -493,14 +560,14 @@ if $cross_compiler; then
       err "While you have an ocamlyacc binary, it cannot be executed" \
           "successfully."
     else
-      echo "CAMLYACC=`./searchpath -p ocamlyacc`" >> Makefile
+      echo "CAMLYACC=`./searchpath -p ocamlyacc`" >&$makefile
     fi
   fi
 
   if [ -z "$target_bindir" ]; then
     err "Cross-compilation requires -target-bindir."
   else
-    echo "TARGET_BINDIR=$target_bindir" >> Makefile
+    echo "TARGET_BINDIR=$target_bindir" >&$makefile
   fi
 fi # cross-compiler
 
@@ -675,8 +742,8 @@ if test $with_sharedlibs = "yes"; then
       sharedcccompopts="-fPIC"
       mksharedlib="$bytecc -shared"
       bytecclinkopts="$bytecclinkopts -Wl,-E"
-      byteccrpath="-Wl,-rpath,"
-      mksharedlibrpath="-Wl,-rpath,"
+      byteccrpath="-Wl,-rpath -Xlinker "
+      mksharedlibrpath="-Wl,-rpath -Xlinker "
       natdynlinkopts="-Wl,-E"
       shared_libraries_supported=true;;
     alpha*-*-osf*)
@@ -967,15 +1034,15 @@ esac
 
 if sh ./searchpath ${TOOLPREF}ranlib; then
   inf "ranlib found"
-  echo "RANLIB=${TOOLPREF}ranlib" >> Makefile
-  echo "RANLIBCMD=${TOOLPREF}ranlib" >> Makefile
+  echo "RANLIB=${TOOLPREF}ranlib" >&$makefile
+  echo "RANLIBCMD=${TOOLPREF}ranlib" >&$makefile
 else
   inf "ranlib not used"
-  echo "RANLIB=${TOOLPREF}ar rs" >> Makefile
-  echo "RANLIBCMD=" >> Makefile
+  echo "RANLIB=${TOOLPREF}ar rs" >&$makefile
+  echo "RANLIBCMD=" >&$makefile
 fi
 
-echo "ARCMD=${TOOLPREF}ar" >> Makefile
+echo "ARCMD=${TOOLPREF}ar" >&$makefile
 
 
 # Write the OS type (Unix or Cygwin)
@@ -987,25 +1054,25 @@ echo "#define OCAML_STDLIB_DIR \"$libdir\"" >> s.h
 
 if (SHELL=/bin/sh; export SHELL; (./hashbang || ./hashbang2) >/dev/null); then
   inf "#! appears to work in shell scripts."
-  case "$target" in
+  case $target in
     *-*-sunos*|*-*-unicos*)
       wrn "We won't use it, though, because under SunOS and Unicos it breaks " \
           "on pathnames longer than 30 characters"
-      echo "HASHBANGSCRIPTS=false" >> Makefile;;
+      echo "HASHBANGSCRIPTS=false" >&$makefile;;
     *-*-cygwin*)
       wrn "We won't use it, though, because of conflicts with .exe extension " \
           "under Cygwin"
-      echo "HASHBANGSCRIPTS=false" >> Makefile;;
+      echo "HASHBANGSCRIPTS=false" >&$makefile;;
     *-*-mingw*)
       inf "We won't use it, though, because it's on the target platform " \
           "it would be used and windows doesn't support it."
-      echo "HASHBANGSCRIPTS=false" >> Makefile;;
+      echo "HASHBANGSCRIPTS=false" >&$makefile;;
     *)
-      echo "HASHBANGSCRIPTS=true" >> Makefile;;
+      echo "HASHBANGSCRIPTS=true" >&$makefile;;
   esac
 else
   inf "No support for #! in shell scripts"
-  echo "HASHBANGSCRIPTS=false" >> Makefile
+  echo "HASHBANGSCRIPTS=false" >&$makefile
 fi
 
 # Use 64-bit file offset if possible
@@ -1088,9 +1155,9 @@ case "$system" in
   *) unix_or_win32="unix"; unixlib="unix"; graphlib="graph";;
 esac
 
-echo "UNIX_OR_WIN32=$unix_or_win32" >> Makefile
-echo "UNIXLIB=$unixlib" >> Makefile
-echo "GRAPHLIB=$graphlib" >> Makefile
+echo "UNIX_OR_WIN32=$unix_or_win32" >&$makefile
+echo "UNIXLIB=$unixlib" >&$makefile
+echo "GRAPHLIB=$graphlib" >&$makefile
 
 otherlibraries="$unixlib str num dynlink bigarray"
 
@@ -1434,8 +1501,8 @@ case "$arch" in
   *)        bng_arch=generic; bng_asm_level=0;;
 esac
 
-echo "BNG_ARCH=$bng_arch" >> Makefile
-echo "BNG_ASM_LEVEL=$bng_asm_level" >> Makefile
+echo "BNG_ARCH=$bng_arch" >&$makefile
+echo "BNG_ASM_LEVEL=$bng_asm_level" >&$makefile
 
 # Determine if the POSIX threads library is supported
 
@@ -1481,8 +1548,8 @@ if test "$pthread_wanted" = "yes"; then
 else
   pthread_link=""
 fi
-echo "PTHREAD_LINK=$pthread_link" >> Makefile
-echo "PTHREAD_CAML_LINK=$pthread_caml_link" >> Makefile
+echo "PTHREAD_LINK=$pthread_link" >&$makefile
+echo "PTHREAD_CAML_LINK=$pthread_caml_link" >&$makefile
 
 # Determine if the bytecode thread library is supported
 
@@ -1574,8 +1641,8 @@ if test "$x11_include" = "not found"; then
   fi
 
   for dir in \
-    $x11_lib_dir          \
-    $x11_try_lib_dir      \
+    "$x11_lib_dir"        \
+    "$x11_try_lib_dir"    \
                           \
     /usr/X11R6/lib64      \
     /usr/X11R6/lib        \
@@ -1621,12 +1688,12 @@ if test "$x11_include" = "not found"; then
     /usr/lib/x86_64-linux-gnu \
     ; \
     do
-    if test -f $dir/libX11.a || \
-       test -f $dir/libX11.so || \
-       test -f $dir/libX11.dll.a || \
-       test -f $dir/libX11.dylib || \
-       test -f $dir/libX11.sa; then
-      if test $dir = /usr/lib; then
+    if test -f "$dir/libX11.a" || \
+       test -f "$dir/libX11.so" || \
+       test -f "$dir/libX11.dll.a" || \
+       test -f "$dir/libX11.dylib" || \
+       test -f "$dir/libX11.sa"; then
+      if test "$dir" = /usr/lib; then
         x11_link="-lX11"
       else
         x11_libs="-L$dir"
@@ -1668,8 +1735,8 @@ else
     otherlibraries="$otherlibraries graph"
   fi
 fi
-echo "X11_INCLUDES=$x11_include" >> Makefile
-echo "X11_LINK=$x11_link" >> Makefile
+echo "X11_INCLUDES=$x11_include" >&$makefile
+echo "X11_LINK=$x11_link" >&$makefile
 
 # Look for BFD library
 
@@ -1677,8 +1744,8 @@ if sh ./hasgot -DPACKAGE=ocaml -i bfd.h && \
    sh ./hasgot -DPACKAGE=ocaml -lbfd -ldl -liberty -lz bfd_openr; then
   inf "BFD library found."
   echo "#define HAS_LIBBFD" >> s.h
-  echo "LIBBFD_LINK=-lbfd -ldl -liberty -lz" >> Makefile
-  echo LIBBFD_INCLUDE= >>Makefile
+  echo "LIBBFD_LINK=-lbfd -ldl -liberty -lz" >&$makefile
+  echo LIBBFD_INCLUDE= >&$makefile
 elif sh ./hasgot -DPACKAGE=ocaml -I/opt/local/include -i bfd.h && \
      sh ./hasgot -DPACKAGE=ocaml -L/opt/local/lib -lbfd -ldl \
                  -liberty -lz -lintl bfd_openr
@@ -1686,13 +1753,13 @@ then
   # MacOSX with binutils from MacPorts
   inf "BFD library found."
   echo "#define HAS_LIBBFD" >> s.h
-  echo "LIBBFD_LINK=-L/opt/local/lib -lbfd -ldl -liberty -lz -lintl" >> Makefile
-  echo LIBBFD_INCLUDE=-I/opt/local/include >>Makefile
+  echo "LIBBFD_LINK=-L/opt/local/lib -lbfd -ldl -liberty -lz -lintl" >&$makefile
+  echo LIBBFD_INCLUDE=-I/opt/local/include >&$makefile
 else
   wrn "BFD library not found, 'objinfo' will be unable to display info" \
       " on .cmxs files."
-  echo "LIBBFD_LINK=" >> Makefile
-  echo "LIBBFD_INCLUDE=" >> Makefile
+  echo "LIBBFD_LINK=" >&$makefile
+  echo "LIBBFD_INCLUDE=" >&$makefile
 fi
 
 # Check whether assembler supports CFI directives
@@ -1741,18 +1808,18 @@ fi
 
 cclibs="$cclibs $mathlib"
 
-echo "BYTECC=$bytecc" >> Makefile
-echo "BYTECCCOMPOPTS=$bytecccompopts" >> Makefile
-echo "BYTECCLINKOPTS=$bytecclinkopts" >> Makefile
-echo "BYTECCLIBS=$cclibs $dllib $curseslibs $pthread_link \
-                 $instrumented_runtime_libs" >> Makefile
-echo "BYTECCRPATH=$byteccrpath" >> Makefile
-echo "EXE=$exe" >> Makefile
-echo "SUPPORTS_SHARED_LIBRARIES=$shared_libraries_supported" >> Makefile
-echo "SHAREDCCCOMPOPTS=$sharedcccompopts" >> Makefile
-echo "MKSHAREDLIBRPATH=$mksharedlibrpath" >> Makefile
-echo "NATDYNLINKOPTS=$natdynlinkopts" >> Makefile
-cat >> Makefile <<EOF
+emit_variable "BYTECC=$bytecc" >&$makefile
+printf %s\\n "BYTECCCOMPOPTS=$bytecccompopts" >&$makefile
+printf %s\\n "BYTECCLINKOPTS=$bytecclinkopts" >&$makefile
+printf %s\\n "BYTECCLIBS=$cclibs $dllib $curseslibs $pthread_link \\
+                 $instrumented_runtime_libs" >&$makefile
+printf %s\\n "BYTECCRPATH=$byteccrpath" >&$makefile
+printf %s\\n "EXE=$exe" >&$makefile
+echo "SUPPORTS_SHARED_LIBRARIES=$shared_libraries_supported" >&$makefile
+echo "SHAREDCCCOMPOPTS=$sharedcccompopts" >&$makefile
+echo "MKSHAREDLIBRPATH=$mksharedlibrpath" >&$makefile
+echo "NATDYNLINKOPTS=$natdynlinkopts" >&$makefile
+cat >&$makefile <<EOF
 SYSLIB=-l\$(1)
 #ml let syslib x = "-l"^x;;
 
@@ -1762,62 +1829,61 @@ MKLIB=${TOOLPREF}ar rc \$(1) \$(2); ${TOOLPREF}ranlib \$(1)
 #ml   Printf.sprintf "${TOOLPREF}ar rc %s %s %s; ${TOOLPREF}ranlib %s"
 #ml                  out opts files out;;
 EOF
-echo "ARCH=$arch" >> Makefile
-echo "MODEL=$model" >> Makefile
-echo "SYSTEM=$system" >> Makefile
-echo "NATIVECC=$nativecc" >> Makefile
-echo "NATIVECCCOMPOPTS=$nativecccompopts" >> Makefile
-echo "NATIVECCPROFOPTS=$nativeccprofopts" >> Makefile
-echo "NATIVECCLINKOPTS=$nativecclinkopts" >> Makefile
-echo "NATIVECCRPATH=$nativeccrpath" >> Makefile
-echo "NATIVECCLIBS=$cclibs $dllib" >> Makefile
-echo "ASM=$as" >> Makefile
-echo "ASPP=$aspp" >> Makefile
-echo "ASPPPROFFLAGS=$asppprofflags" >> Makefile
-echo "PROFILING=$profiling" >> Makefile
-echo "DYNLINKOPTS=$dllib" >> Makefile
-echo "OTHERLIBRARIES=$otherlibraries" >> Makefile
-echo "CC_PROFILE=$cc_profile" >> Makefile
-echo "SYSTHREAD_SUPPORT=$systhread_support" >> Makefile
-echo "PARTIALLD=$partialld" >> Makefile
-echo "PACKLD=\$(PARTIALLD) \$(NATIVECCLINKOPTS) -o " \
-  | sed -e 's/ $/\\ /' >> Makefile
-echo "DLLCCCOMPOPTS=$dllccompopts" >> Makefile
-echo "IFLEXDIR=$iflexdir" >> Makefile
-echo "O=o" >> Makefile
-echo "A=a" >> Makefile
-echo "SO=$SO" >> Makefile
-echo "EXT_OBJ=.o" >> Makefile
-echo "EXT_ASM=.s" >> Makefile
-echo "EXT_LIB=.a" >> Makefile
-echo "EXT_DLL=.$SO" >> Makefile
-echo "EXTRALIBS=" >> Makefile
-echo "CCOMPTYPE=cc" >> Makefile
-echo "TOOLCHAIN=$TOOLCHAIN" >> Makefile
-echo "NATDYNLINK=$natdynlink" >> Makefile
-echo "CMXS=$cmxs" >> Makefile
-echo "MKEXE=$mkexe" >> Makefile
-echo "MKEXEDEBUGFLAG=$mkexedebugflag" >> Makefile
-echo "MKDLL=$mksharedlib" >> Makefile
-echo "MKMAINDLL=$mkmaindll" >> Makefile
-echo "RUNTIMED=${debugruntime}" >>Makefile
+echo "ARCH=$arch" >&$makefile
+echo "MODEL=$model" >&$makefile
+echo "SYSTEM=$system" >&$makefile
+echo "NATIVECC=$nativecc" >&$makefile
+echo "NATIVECCCOMPOPTS=$nativecccompopts" >&$makefile
+echo "NATIVECCPROFOPTS=$nativeccprofopts" >&$makefile
+echo "NATIVECCLINKOPTS=$nativecclinkopts" >&$makefile
+echo "NATIVECCRPATH=$nativeccrpath" >&$makefile
+echo "NATIVECCLIBS=$cclibs $dllib" >&$makefile
+echo "ASM=$as" >&$makefile
+echo "ASPP=$aspp" >&$makefile
+echo "ASPPPROFFLAGS=$asppprofflags" >&$makefile
+echo "PROFILING=$profiling" >&$makefile
+echo "DYNLINKOPTS=$dllib" >&$makefile
+echo "OTHERLIBRARIES=$otherlibraries" >&$makefile
+echo "CC_PROFILE=$cc_profile" >&$makefile
+echo "SYSTHREAD_SUPPORT=$systhread_support" >&$makefile
+printf %s\\n "PARTIALLD=$partialld" >&$makefile
+printf 'PACKLD=$(PARTIALLD) $(NATIVECCLINKOPTS) -o \\ \n' >&$makefile
+echo "DLLCCCOMPOPTS=$dllccompopts" >&$makefile
+echo "IFLEXDIR=$iflexdir" >&$makefile
+echo "O=o" >&$makefile
+echo "A=a" >&$makefile
+echo "SO=$SO" >&$makefile
+echo "EXT_OBJ=.o" >&$makefile
+echo "EXT_ASM=.s" >&$makefile
+echo "EXT_LIB=.a" >&$makefile
+echo "EXT_DLL=.$SO" >&$makefile
+echo "EXTRALIBS=" >&$makefile
+echo "CCOMPTYPE=cc" >&$makefile
+echo "TOOLCHAIN=$TOOLCHAIN" >&$makefile
+echo "NATDYNLINK=$natdynlink" >&$makefile
+echo "CMXS=$cmxs" >&$makefile
+echo "MKEXE=$mkexe" >&$makefile
+echo "MKEXEDEBUGFLAG=$mkexedebugflag" >&$makefile
+echo "MKDLL=$mksharedlib" >&$makefile
+echo "MKMAINDLL=$mkmaindll" >&$makefile
+echo "RUNTIMED=${debugruntime}" >&$makefile
 if $shared_libraries_supported; then
-  echo "SHARED=shared" >>Makefile
+  echo "SHARED=shared" >&$makefile
 else
-  echo "SHARED=noshared" >>Makefile
+  echo "SHARED=noshared" >&$makefile
 fi
-echo "RUNTIMEI=${with_instrumented_runtime}" >>Makefile
-echo "WITH_DEBUGGER=${with_debugger}" >>Makefile
-echo "WITH_OCAMLDOC=${with_ocamldoc}" >>Makefile
-echo "ASM_CFI_SUPPORTED=$asm_cfi_supported" >> Makefile
-echo "WITH_FRAME_POINTERS=$with_frame_pointers" >> Makefile
-echo "TARGET=$target" >> Makefile
-echo "HOST=$host" >> Makefile
+echo "RUNTIMEI=${with_instrumented_runtime}" >&$makefile
+echo "WITH_DEBUGGER=${with_debugger}" >&$makefile
+echo "WITH_OCAMLDOC=${with_ocamldoc}" >&$makefile
+echo "ASM_CFI_SUPPORTED=$asm_cfi_supported" >&$makefile
+echo "WITH_FRAME_POINTERS=$with_frame_pointers" >&$makefile
+echo "TARGET=$target" >&$makefile
+echo "HOST=$host" >&$makefile
 if [ "$ostype" = Cygwin ]; then
-  echo "DIFF=diff -q --strip-trailing-cr" >>Makefile
+  echo "DIFF=diff -q --strip-trailing-cr" >&$makefile
 fi
-echo "FLAMBDA=$flambda" >> Makefile
-echo "MAX_TESTSUITE_DIR_RETRIES=$max_testsuite_dir_retries" >> Makefile
+echo "FLAMBDA=$flambda" >&$makefile
+echo "MAX_TESTSUITE_DIR_RETRIES=$max_testsuite_dir_retries" >&$makefile
 
 
 rm -f tst hasgot.c
