configure: Check C99 conformance by using the preprocessor
Recently there was a check added to test for C99 conformance of the
target compiler. The configure script builds a small test program and
runs it to detect C99 conformance. This fails in case of
cross-compilation, as the program build for the target arch cannot run
on the host arch.

Solve this by examining the preprocessor output of the target compiler.

Signed-off-by: Stefan Hellermann <stefan@the2masters.de>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -433,23 +433,19 @@ export cc cclibs verbose
 
 # Check C compiler.
 
-cc="$bytecc $bytecccompopts $bytecclinkopts" sh ./runtest ansi.c
-case $? in
-  0) inf "The C compiler is ISO C99 compliant." ;;
-  1) wrn "The C compiler is ANSI / ISO C90 compliant, but not ISO C99" \
-         "compliant.";;
-  2) err "The C compiler $cc is not ISO C compliant.\n" \
-         "You need an ISO C99 compiler to build OCaml.";;
-  *)
-     if $cross_compiler; then
-       wrn "Unable to compile the test program.\n" \
-           "This failure is expected for cross-compilation:\n" \
-           "we will assume the C compiler is ISO C99-compliant."
-     else
-       err "Unable to compile the test program.\n" \
-           "Make sure the C compiler $cc is properly installed."
-     fi;;
-esac
+cc="$bytecc $bytecccompopts $bytecclinkopts" ret=`sh ./preprocesstest ansi.c`
+if test "$?" -eq 0; then
+  case $ret in
+    0) inf "The C compiler is ISO C99 compliant." ;;
+    1) wrn "The C compiler is ANSI / ISO C90 compliant, but not ISO C99" \
+           "compliant.";;
+    *) err "The C compiler $cc is not ISO C compliant.\n" \
+           "You need an ISO C99 compiler to build OCaml.";;
+  esac
+else
+  err "Unable to compile the test program.\n" \
+      "Make sure the C compiler $cc is properly installed."
+fi
 
 # For cross-compilation, we need a host-based ocamlrun and ocamlyacc,
 # and the user must specify the target BINDIR
