Sources C convertis en ANSI C
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@1696 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -142,6 +142,19 @@ echo "BYTECCLINKOPTS=$bytecclinkopts" >> Makefile
 cc="$bytecc $bytecclinkopts"
 export cc cclibs
 
+# Check C compiler
+
+sh ./runtest ansi.c
+case $? in
+  0) echo "The C compiler is ANSI-compliant.";;
+  1) echo "The C compiler $cc is not ANSI-compliant."
+     echo "You need an ANSI C compiler to build Objective Caml."
+     exit 2;;
+  *) echo "Unable to compiler the test program."
+     echo "Make sure the C compiler $cc is properly installed."
+     exit 2;;
+esac
+
 # Check the sizes of data types
 
 echo "Checking the sizes of integers and pointers..."
