Compressed backtraces with OCAML_COMPRESSED_BACKTRACES

diff --git a/testsuite/tests/backtrace/Makefile b/testsuite/tests/backtrace/Makefile
--- a/testsuite/tests/backtrace/Makefile
+++ b/testsuite/tests/backtrace/Makefile
@@ -19,6 +19,7 @@ EXECNAME=program$(EXE)
 ABCDFILES=backtrace.ml
 OTHERFILES=backtrace2.ml backtrace3.ml raw_backtrace.ml \
            backtrace_deprecated.ml backtrace_slots.ml
+CYCLEFILES= backtrace_cycle1.ml backtrace_cycle2.ml backtrace_cycle3.ml
 INLININGFILES=inline_test.ml inline_traversal_test.ml
 OTHERFILESNOINLINING=pr6920_why_at.ml pr6920_why_swallow.ml
 OTHERFILESNOINLINING_NATIVE=backtraces_and_finalizers.ml
@@ -68,6 +69,17 @@ byte:
 			| $(LOCATIONFILTER) >$$F.byte.result 2>&1; \
 	  $(DIFF) $$F.byte.reference $$F.byte.result >/dev/null \
 	  && echo " => passed" || echo " => failed"; \
+	done;
+	@for file in $(CYCLEFILES); do \
+	  rm -f program program.exe; \
+	  $(OCAMLC) -g -o $(EXECNAME) $$file; \
+	  printf " ... testing '$$file' with ocamlc:"; \
+	  F="`basename $$file .ml`"; \
+	  (OCAMLRUNPARAM=$$OCAMLRUNPARAM,b=1 OCAML_COMPRESSED_BACKTRACE=1 \
+            $(OCAMLRUN) $(EXECNAME) $$arg || true) \
+	       >$$F.byte.result 2>&1; \
+	  $(DIFF) $$F.byte.reference $$F.byte.result >/dev/null \
+	  && echo " => passed" || (echo " => failed"; cat $$F.byte.result); \
 	done
 
 .PHONY: skip
@@ -142,8 +154,18 @@ native:
 		 	| $(LOCATIONFILTER) >$$F.O3.result; \
 	  $(DIFF) $$F.native.reference $$F.O3.result >/dev/null \
 	  && echo " => passed" || echo " => failed"; \
-	done
-
+	done;
+	@for file in $(CYCLEFILES); do \
+	  rm -f program program.exe; \
+	  $(OCAMLOPT) -g -o $(EXECNAME) $$file; \
+	  printf " ... testing '$$file' with ocamlopt:"; \
+	  F="`basename $$file .ml`"; \
+	  (OCAMLRUNPARAM=$$OCAMLRUNPARAM,b=1 OCAML_COMPRESSED_BACKTRACE=1 \
+            ./$(EXECNAME) $$arg || true) \
+	       >$$F.native.result 2>&1; \
+	  $(DIFF) $$F.native.reference $$F.native.result >/dev/null \
+	  && echo " => passed" || (echo " => failed"; cat $$F.native.result) \
+	done;
 
 .PHONY: promote
 promote: defaultpromote
