Eliminate testsuite ulimit warning on Cygwin
Cygwin doesn't allow the stack limit (uname -s) to be changed, though it
can be queried. Alter the test so that the stack limit is only changed if
it is either unlimited or very large (and skip the tests if ulimit returns
an error)

diff --git a/testsuite/tests/runtime-errors/Makefile b/testsuite/tests/runtime-errors/Makefile
--- a/testsuite/tests/runtime-errors/Makefile
+++ b/testsuite/tests/runtime-errors/Makefile
@@ -30,20 +30,37 @@ compile:
 	@grep -q HAS_STACK_OVERFLOW_DETECTION $(TOPDIR)/config/s.h \
 	  || rm -f stackoverflow.native$(EXE)
 
+# Cygwin doesn't allow the stack limit to be changed - the 4096 is
+# intended to be larger than the its default stack size. The logic
+# causes the test to be skipped if the stacksize cannot be brought
+# below this value (uname -s value exits with an error status in Cygwin)
 .PHONY: run
 run:
-	@ulimit -s 1024; \
+	@ul=`ulimit -s`; \
+	 if ( [ "$$ul" = "unlimited" ] || [ $$ul -gt 4096 ] ) ; then \
+	   ulimit -s 1024 && ul=1 || ul=0 ; \
+	 else \
+	   ul=1; \
+	 fi; \
 	 for f in *.bytecode; do \
 	  printf " ... testing '$$f':"; \
-	  $(OCAMLRUN) ./$$f >$$f.result 2>&1 || true; \
-	  DIFF="$(DIFF)" sh $$f.checker \
-	  && echo " => passed" || echo " => failed"; \
+	  if [ $$ul -eq 1 ] ; then \
+	    $(OCAMLRUN) ./$$f >$$f.result 2>&1 || true; \
+	    DIFF="$(DIFF)" sh $$f.checker \
+	    && echo " => passed" || echo " => failed"; \
+	  else \
+	    echo " => unexpected error"; \
+	  fi; \
 	  fn=`basename $$f bytecode`native; \
 	  if $(BYTECODE_ONLY) || [ ! -f "$${fn}$(EXE)" ] ; then : ; else \
 	    printf " ... testing '$$fn':"; \
-	    ./$${fn}$(EXE) >$$fn.result 2>&1 || true; \
-	    DIFF="$(DIFF)" sh $$fn.checker \
-	    && echo " => passed" || echo " => failed"; \
+	    if [ $$ul -eq 1 ] ; then \
+	      ./$${fn}$(EXE) >$$fn.result 2>&1 || true; \
+	      DIFF="$(DIFF)" sh $$fn.checker \
+	      && echo " => passed" || echo " => failed"; \
+	    else \
+	      echo " => unexpected error"; \
+	    fi; \
 	  fi; \
 	done
 
