backport changes to make tests work on different architectures
git-svn-id: http://caml.inria.fr/svn/ocaml/version/4.00@13575 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/tests/runtime-errors/Makefile b/testsuite/tests/runtime-errors/Makefile
--- a/testsuite/tests/runtime-errors/Makefile
+++ b/testsuite/tests/runtime-errors/Makefile
@@ -7,20 +7,21 @@ compile:
 	  $(OCAMLC) -w a -o `basename $$f ml`bytecode $$f; \
 	  test -z "$(BYTECODE_ONLY)" && $(OCAMLOPT) -w a -o `basename $$f ml`native $$f || true; \
 	done
-	@if [ ! `grep -c HAS_STACK_OVERFLOW_DETECTION ../../../config/s.h` ]; then \
-	  test -z "$(BYTECODE_ONLY)" && rm -f stackoverflow.byte stackoverflow.native || true; \
+	@if [ `grep -c HAS_STACK_OVERFLOW_DETECTION ../../../config/s.h` -eq 0 ]; then \
+	  rm -f stackoverflow.native || true; \
 	fi
 
 run:
 	@ulimit -s 1024; \
-         for f in *.bytecode; do \
+	 for f in *.bytecode; do \
 	  printf " ... testing '$$f':"; \
-	  (./$$f > $$f.result 2>&1; true); \
+	  (./$$f > $$f.result 2>&1 || true); \
 	  $(DIFF) $$f.reference $$f.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
-	  if [ -z "$(BYTECODE_ONLY)" ]; then \
-	    printf " ... testing '`basename $$f bytecode`native':"; \
-	    (./`basename $$f bytecode`native > `basename $$f bytecode`native.result 2>&1; true); \
-	    $(DIFF) `basename $$f bytecode`native.reference `basename $$f bytecode`native.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
+	  fn=`basename $$f bytecode`native; \
+	  if [ -z "$(BYTECODE_ONLY)" -a -f "$$fn" ]; then \
+	    printf " ... testing '$$fn':"; \
+	    (./$$fn > $$fn.result 2>&1 || true); \
+	    $(DIFF) $$fn.reference $$fn.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
 	  fi; \
 	done
 
