do not test stack overflow on architectures that do not support it
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@13523 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/tests/runtime-errors/Makefile b/testsuite/tests/runtime-errors/Makefile
--- a/testsuite/tests/runtime-errors/Makefile
+++ b/testsuite/tests/runtime-errors/Makefile
@@ -25,14 +25,17 @@ compile:
 
 run:
 	@ulimit -s 1024; \
-         for f in *.bytecode; do \
+	 for f in *.bytecode; do \
 	  printf " ... testing '$$f':"; \
 	  (./$$f > $$f.result 2>&1; true); \
-	  $(DIFF) $$f.reference $$f.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
-	  if [ -z "$(BYTECODE_ONLY)" ]; then \
-	    printf " ... testing '`basename $$f bytecode`native':"; \
-	    (./`basename $$f bytecode`native > `basename $$f bytecode`native.result 2>&1; true); \
-	    $(DIFF) `basename $$f bytecode`native.reference `basename $$f bytecode`native.result > /dev/null || (echo " => failed" && exit 1) && echo " => passed"; \
+	  $(DIFF) $$f.reference $$f.result > /dev/null || (echo " => failed" &&\
+ exit 1) && echo " => passed"; \
+	  fn=`basename $$f bytecode`native; \
+	  if [ -z "$(BYTECODE_ONLY)" -a -f "$$fn" ]; then \
+	    printf " ... testing '$$fn':"; \
+	    (./$$fn > $$fn.result 2>&1; true); \
+	    $(DIFF) $$fn.reference $$fn.result > /dev/null || (echo " => failed\
+" && exit 1) && echo " => passed"; \
 	  fi; \
 	done
 
