Merge ocmal 4.00 r12217 -> r12778
git-svn-id: http://caml.inria.fr/svn/ocaml/branches/jo400@12875 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -41,19 +41,20 @@ run-all:
 
 run-file:
 	@printf " $(DESC)"
-	$(COMP) $(COMPFLAGS) $(FILE) -o program
+	@rm -f program program.exe
+	@$(COMP) $(COMPFLAGS) $(FILE) -o program
 	@if [ -f `basename $(FILE) ml`runner ]; then \
 	  sh `basename $(FILE) ml`runner; \
 	else \
 	  ./program $(PROGRAM_ARGS) > `basename $(FILE) ml`result; \
-	fi
+	fi || (echo " => failed" && exit 1)
 	@if [ -f `basename $(FILE) ml`checker ]; then \
 	  sh `basename $(FILE) ml`checker; \
 	else \
-	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1); \
-	fi
+	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null; \
+	fi || (echo " => failed" && exit 1)
 
 promote: defaultpromote
 
 clean: defaultclean
-	@rm -f *.result ./program
+	@rm -f *.result ./program program.exe
