fix missing "failed" message when .checker is present
git-svn-id: http://caml.inria.fr/svn/ocaml/version/4.00@12618 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -51,8 +51,8 @@ run-file:
 	@if [ -f `basename $(FILE) ml`checker ]; then \
 	  sh `basename $(FILE) ml`checker; \
 	else \
-	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1); \
-	fi
+	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null; \
+	fi || (echo " => failed" && exit 1)
 
 promote: defaultpromote
 
