Tests moved to 'lib-threads'
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@9593 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -36,8 +36,16 @@ run-all:
 run-file:
 	@echo -n " $(DESC)"
 	@$(COMP) $(COMPFLAGS) $(FILE) -o program
-	@./program $(PROGRAM_ARGS) > `basename $(FILE) ml`result
-	@diff -q `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1)
+	@if [ -f `basename $(FILE) ml`runner ]; then \
+	  sh `basename $(FILE) ml`runner; \
+	else \
+	  ./program $(PROGRAM_ARGS) > `basename $(FILE) ml`result; \
+	fi
+	@if [ -f `basename $(FILE) ml`checker ]; then \
+	  sh `basename $(FILE) ml`checker; \
+	else \
+	  diff -q `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1); \
+	fi
 
 clean: defaultclean
 	@rm -f *.result ./program
