Promote to 4.04.2 => bootstrap succeeded

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -1,14 +1,17 @@
-#########################################################################
-#                                                                       #
-#                                 OCaml                                 #
-#                                                                       #
-#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
-#                                                                       #
-#   Copyright 2010 Institut National de Recherche en Informatique et    #
-#   en Automatique.  All rights reserved.  This file is distributed     #
-#   under the terms of the Q Public License version 1.0.                #
-#                                                                       #
-#########################################################################
+#**************************************************************************
+#*                                                                        *
+#*                                 OCaml                                  *
+#*                                                                        *
+#*                 Xavier Clerc, SED, INRIA Rocquencourt                  *
+#*                                                                        *
+#*   Copyright 2010 Institut National de Recherche en Informatique et     *
+#*     en Automatique.                                                    *
+#*                                                                        *
+#*   All rights reserved.  This file is distributed under the terms of    *
+#*   the GNU Lesser General Public License version 2.1, with the          *
+#*   special exception on linking described in the file LICENSE.          *
+#*                                                                        *
+#**************************************************************************
 
 CC=$(NATIVECC) $(NATIVECCCOMPOPTS)
 FC=$(FORTAN_COMPILER)
@@ -16,34 +19,48 @@ CMO_FILES=$(MODULES:=.cmo)
 CMX_FILES=$(MODULES:=.cmx)
 CMA_FILES=$(LIBRARIES:=.cma)
 CMXA_FILES=$(LIBRARIES:=.cmxa)
-O_FILES=$(C_FILES:=.o)
+O_FILES=$(F_FILES:=.o) $(C_FILES:=.o)
 
 CUSTOM_FLAG=`if [ -n "$(C_FILES)" ]; then echo '-custom'; fi`
 ADD_CFLAGS+=$(CUSTOM_FLAG)
 MYRUNTIME=`if [ -z "$(C_FILES)$(CUSTOM)" ]; then echo '$(OCAMLRUN)'; fi`
-FORTRAN_LIB=`if [ -n "$(F_FILES)" ]; then echo '$(FORTRAN_LIBRARY)'; fi`
+FORTRAN_LIB=`if [ -n "$(F_FILES)" ]; then echo $(FORTRAN_LIBRARY); fi`
 ADD_CFLAGS+=$(FORTRAN_LIB)
 ADD_OPTFLAGS+=$(FORTRAN_LIB)
+
+C_INCLUDES+=-I $(CTOPDIR)/byterun -I$(CTOPDIR)/otherlibs/bigarray
+
+GENERATED_SOURCES=
+
+SKIP=false
 
 .PHONY: check
 check:
 	@if [ -n "$(FORTRAN_COMPILER)" -o -z "$(F_FILES)" ]; then \
 	  $(SET_LD_PATH) $(MAKE) run-all; \
+	else \
+	  $(MAKE) C_FILES= F_FILES= SKIP=true run-all; \
 	fi
 
 .PHONY: run-all
 run-all:
 	@for file in $(C_FILES); do \
-	  $(CC) -c -I$(PREFIX)/lib/ocaml/caml $$file.c; \
+	  $(OCAMLC) -c $(C_INCLUDES) -c $$file.c; \
 	done;
 	@for file in $(F_FILES); do \
-	  $(FORTRAN_COMPILER) -c -I$(PREFIX)/lib/ocaml/caml $$file.f; \
+	  $(FORTRAN_COMPILER) -c $$file.f; \
 	done;
 	@for file in *.ml; do \
-	  if [ -f `basename $$file ml`precheck ]; then \
-	    CANKILL=$(CANKILL) sh `basename $$file ml`precheck || continue; \
-	  fi; \
 	  printf " ... testing '$$file':"; \
+	  if $(SKIP) ; then \
+	    echo " => skipped"; continue; \
+	  fi; \
+	  if [ -f `basename $$file ml`precheck ]; then \
+	    if ! TOOLCHAIN=$(TOOLCHAIN) sh `basename $$file ml`precheck ; then \
+	      echo " => skipped"; \
+	      continue; \
+	    fi; \
+	  fi; \
 	  $(MAKE) run-file DESC=ocamlc COMP='$(OCAMLC)' \
 	          RUNTIME='$(MYRUNTIME)' \
 	          COMPFLAGS='-w a $(ADD_COMPFLAGS) $(ADD_CFLAGS) $(O_FILES) \
@@ -80,10 +97,23 @@ run-all:
 	  && echo " => passed" || echo " => failed"; \
 	done
 
+# On Windows, nefarious software (specifically Windows Defender) can prevent
+# executable files being deleted while it scans them. Unfortunately, it does
+# this by allowing the delete system call (either via rm -f or cmd /c del) to
+# complete with success but the file can linger for seconds or even minutes
+# until it suddenly disappears. During this time, the file cannot be overwritten
+# but it can be renamed, hence the odd use of mktemp. Some tests compiled with
+# flambda seem to be consistently "interesting" to Windows Defender. Note that
+# the interference doesn't appear to affect the execution of the tests.
 .PHONY: run-file
 run-file:
 	@printf " $(DESC)"
-	@rm -f program program.exe
+	@test -e program.exe && { \
+	  T="`mktemp -p .`"; \
+	  mv -f program.exe "$$T"; \
+	  rm -f "$$T"; \
+	} || true
+	@rm -f program program$(EXE)
 	@$(COMP) $(COMPFLAGS) $(FILE) -o program$(EXE)
 	@F="`basename $(FILE) .ml`"; \
 	if [ -f $$F.runner ]; then \
@@ -93,9 +123,15 @@ run-file:
 	fi \
 	&& \
 	if [ -f $$F.checker ]; then \
-	  DIFF="$(DIFF)" SORT="$(SORT)" sh $$F.checker; \
+	  DIFF="$(DIFF)" SORT="$(SORT)" sh $$F.checker || { \
+	    printf "  Error: output checker failed!\n"; \
+	    exit 1; \
+	  }; \
 	else \
-	  $(DIFF) $$F.reference $$F.result >/dev/null; \
+	  $(DIFF) $$F.reference $$F.result >/dev/null || { \
+	    printf "  Error: results don't match reference output!\n"; \
+	    exit 1; \
+	  }; \
 	fi
 
 .PHONY: promote
@@ -103,4 +139,4 @@ promote: defaultpromote
 
 .PHONY: clean
 clean: defaultclean
-	@rm -f *.result program program.exe
+	@rm -f *.result program program.exe $(GENERATED_SOURCES)
diff --git a/testsuite/tests/asmcomp/Makefile b/testsuite/tests/asmcomp/Makefile
--- a/testsuite/tests/asmcomp/Makefile
+++ b/testsuite/tests/asmcomp/Makefile
@@ -1,23 +1,24 @@
-#########################################################################
-#                                                                       #
-#                                 OCaml                                 #
-#                                                                       #
-#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
-#                                                                       #
-#   Copyright 2010 Institut National de Recherche en Informatique et    #
-#   en Automatique.  All rights reserved.  This file is distributed     #
-#   under the terms of the Q Public License version 1.0.                #
-#                                                                       #
-#########################################################################
+#**************************************************************************
+#*                                                                        *
+#*                                OCaml                                   *
+#*                                                                        *
+#*                 Xavier Clerc, SED, INRIA Rocquencourt                  *
+#*                                                                        *
+#*   Copyright 2010 Institut National de Recherche en Informatique et     *
+#*     en Automatique.                                                    *
+#*                                                                        *
+#*   All rights reserved.  This file is distributed under the terms of    *
+#*   the GNU Lesser General Public License version 2.1, with the          *
+#*   special exception on linking described in the file LICENSE.          *
+#*                                                                        *
+#**************************************************************************
 
 BASEDIR=../..
-
-CC=$(NATIVECC)
-CFLAGS=$(NATIVECCCOMPOPTS) -g
 
 INCLUDES=\
   -I $(OTOPDIR)/utils \
   -I $(OTOPDIR)/typing \
+  -I $(OTOPDIR)/middle_end \
   -I $(OTOPDIR)/bytecomp \
   -I $(OTOPDIR)/asmcomp
 
@@ -27,16 +28,16 @@ OTHEROBJS=\
 
 OBJS=parsecmmaux.cmo parsecmm.cmo lexcmm.cmo
 
-ADD_COMPFLAGS=$(INCLUDES) -g
+ADD_COMPFLAGS=$(INCLUDES) -w -40 -g
 
 default:
-	@if $(BYTECODE_ONLY) || [ -z "$(ASPP)" ]; then : ; else \
+	@if $(BYTECODE_ONLY) || $(SKIP) ; then $(MAKE) skips ; else \
 	  $(MAKE) all; \
 	fi
 
 all:
-	$(MAKE) arch codegen
-	$(MAKE) tests
+	@$(MAKE) arch codegen
+	@$(MAKE) tests
 
 codegen: parsecmm.ml lexcmm.ml $(OBJS:.cmo=.cmi) $(OBJS) main.cmo
 	@$(OCAMLC) $(LINKFLAGS) -o codegen $(OTHEROBJS) $(OBJS) main.cmo
@@ -47,24 +48,82 @@ parsecmm.mli parsecmm.ml: parsecmm.mly
 lexcmm.ml: lexcmm.mll
 	@$(OCAMLLEX) -q lexcmm.mll
 
-MLCASES=optargs staticalloc
+MLCASES=optargs staticalloc bind_tuples is_static register_typing \
+  register_typing_switch
+ARGS_is_static=-I $(OTOPDIR)/byterun is_in_static_data.c
+MLCASES_FLAMBDA=is_static_flambda unrolling_flambda unrolling_flambda2 \
+  static_float_array_flambda static_float_array_flambda_opaque
+ARGS_is_static_flambda=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c is_static_flambda_dep.ml
+ARGS_static_float_array_flambda=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c simple_float_const.ml
+ARGS_static_float_array_flambda_opaque=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c -opaque simple_float_const_opaque.ml
 
 CASES=fib tak quicksort quicksort2 soli \
       arith checkbound tagged-fib tagged-integr tagged-quicksort tagged-tak
-ARGS_fib=-ccopt -DINT_INT -ccopt -DFUN=fib main.c
-ARGS_tak=-ccopt -DUNIT_INT -ccopt -DFUN=takmain main.c
-ARGS_quicksort=-ccopt -DSORT -ccopt -DFUN=quicksort main.c
-ARGS_quicksort2=-ccopt -DSORT -ccopt -DFUN=quicksort main.c
-ARGS_soli=-ccopt -DUNIT_INT -ccopt -DFUN=solitaire main.c
-ARGS_integr=-ccopt -DINT_FLOAT -ccopt -DFUN=test main.c
+ARGS_fib=-DINT_INT -DFUN=fib main.c
+ARGS_tak=-DUNIT_INT -DFUN=takmain main.c
+ARGS_quicksort=-DSORT -DFUN=quicksort main.c
+ARGS_quicksort2=-DSORT -DFUN=quicksort main.c
+ARGS_soli=-DUNIT_INT -DFUN=solitaire main.c
+ARGS_integr=-DINT_FLOAT -DFUN=test main.c
 ARGS_arith=mainarith.c
-ARGS_checkbound=-ccopt -DCHECKBOUND main.c
-ARGS_tagged-fib=-ccopt -DINT_INT -ccopt -DFUN=fib main.c
-ARGS_tagged-integr=-ccopt -DINT_FLOAT -ccopt -DFUN=test main.c
-ARGS_tagged-quicksort=-ccopt -DSORT -ccopt -DFUN=quicksort main.c
-ARGS_tagged-tak=-ccopt -DUNIT_INT -ccopt -DFUN=takmain main.c
+ARGS_checkbound=-DCHECKBOUND main.c
+ARGS_tagged-fib=-DINT_INT -DFUN=fib main.c
+ARGS_tagged-integr=-DINT_FLOAT -DFUN=test main.c
+ARGS_tagged-quicksort=-DSORT -DFUN=quicksort main.c
+ARGS_tagged-tak=-DUNIT_INT -DFUN=takmain main.c
+ARGS_staticalloc=-I $(OTOPDIR)/utils config.cmx
 
-tests: $(CASES:=.o)
+skips:
+	@for c in $(CASES) $(MLCASES) $(MLCASES_FLAMBDA); do \
+	  echo " ... testing '$$c': => skipped"; \
+	done
+
+one_ml:
+	@$(OCAMLOPT) $(ARGS_$(NAME)) -o $(NAME).exe $(NAME).ml && \
+	./$(NAME).exe && echo " => passed" || echo " => failed"
+
+one_ml_flambda:
+	@if $(FLAMBDA); then \
+	   $(OCAMLOPT) $(ARGS_$(NAME)) -o $(NAME).exe $(NAME).ml && \
+	   ./$(NAME).exe && echo " => passed" || echo " => failed"; \
+	 else \
+	   echo " => skipped"; \
+	 fi
+
+one:
+	@$(call CC,$(NAME).out $(ARGS_$(NAME)) $(NAME).$(O) $(ARCH).$(O)) \
+	&& echo " => passed" || echo " => failed"
+
+clean: defaultclean
+	@rm -f ./codegen *.out *.out.manifest *.$(O) *.exe
+	@rm -f parsecmm.ml parsecmm.mli lexcmm.ml
+	@rm -f $(CASES:=.s)
+
+include $(BASEDIR)/makefiles/Makefile.common
+
+ifeq "$(CCOMPTYPE)-$(ARCH)" "msvc-amd64"
+# these tests are not ported to MSVC64 yet
+SKIP=true
+else
+SKIP=false
+endif
+
+ifeq "$(WITH_SPACETIME)" "true"
+# These tests have not been ported for Spacetime
+SKIP=true
+endif
+
+ifeq ($(CCOMPTYPE),msvc)
+CC=set -o pipefail ; $(NATIVECC) $(CFLAGS) /Fe$(1) | tail -n +2
+CFLAGS=$(NATIVECCCOMPOPTS)
+else
+CC=$(NATIVECC) $(CFLAGS) -o $(1)
+CFLAGS=$(NATIVECCCOMPOPTS) -g
+endif
+tests: $(CASES:=.$(O))
 	@for c in $(CASES); do \
 	  printf " ... testing '$$c':"; \
 	  $(MAKE) one NAME=$$c; \
@@ -73,25 +132,15 @@ tests: $(CASES:=.o)
 	  printf " ... testing '$$c':"; \
           $(MAKE) one_ml NAME=$$c; \
         done
-
-one_ml:
-	@$(OCAMLOPT) -o $(NAME).exe $(NAME).ml && \
-	./$(NAME).exe && echo " => passed" || echo " => failed"
-
-one:
-	@$(OCAMLOPT) -o $(NAME).out $(ARGS_$(NAME)) $(NAME).o $(ARCH).o \
-	&& echo " => passed" || echo " => failed"
-
-clean: defaultclean
-	@rm -f ./codegen *.out *.o *.obj *.exe
-	@rm -f parsecmm.ml parsecmm.mli lexcmm.ml
-	@rm -f $(CASES:=.s)
-
-include $(BASEDIR)/makefiles/Makefile.common
-
-power.o: power-$(SYSTEM).o
-	@cp power-$(SYSTEM).o power.o
+	@for c in $(MLCASES_FLAMBDA); do \
+	  printf " ... testing '$$c':"; \
+          $(MAKE) one_ml_flambda NAME=$$c; \
+        done
 
 promote:
 
-arch: $(ARCH).o
+arch: $(ARCH).$(O)
+
+i386.obj: i386nt.asm
+	@set -o pipefail ; \
+	$(ASM) $@ $^ | tail -n +2
diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -1,15 +1,17 @@
-#########################################################################
-#                                                                       #
-#                                 OCaml                                 #
-#                                                                       #
-#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
-#                                                                       #
-#   Copyright 2010 Institut National de Recherche en Informatique et    #
-#   en Automatique.  All rights reserved.  This file is distributed     #
-#   under the terms of the Q Public License version 1.0.                #
-#                                                                       #
-#########################################################################
-
+#**************************************************************************
+#*                                                                        *
+#*                                OCaml                                   *
+#*                                                                        *
+#*                 Xavier Clerc, SED, INRIA Rocquencourt                  *
+#*                                                                        *
+#*   Copyright 2010 Institut National de Recherche en Informatique et     *
+#*     en Automatique.                                                    *
+#*                                                                        *
+#*   All rights reserved.  This file is distributed under the terms of    *
+#*   the GNU Lesser General Public License version 2.1, with the          *
+#*   special exception on linking described in the file LICENSE.          *
+#*                                                                        *
+#**************************************************************************
 
 BASEDIR=../..
 
@@ -22,35 +24,39 @@ default:
 	@case " $(OTHERLIBRARIES) " in \
 	  *' unix '*) $(SET_LD_PATH) $(MAKE) run-byte; \
 	              $(SET_LD_PATH) $(MAKE) run-opt;; \
+	  *) $(MAKE) skip;; \
 	esac
 
+.PHONY: common
+common:
+	@$(CC) -c callbackprim.c
 
-.PHONY: run-byte
-run-byte:
-	@for f in *.ml; do \
-	  printf " ... testing 'bytecode':"; \
-	  F=`basename $$f .ml`; \
-		$(CC) -c $$F.c; \
-		$(OCAMLC) $(COMPFLAGS) -c $$F.mli; \
-		$(OCAMLC) $(COMPFLAGS) -c $$F.ml; \
-		$(OCAMLC) $(COMPFLAGS) -o ./$$F.byte$(EXE) -custom unix.cma $$F.$(O) $$F.cmo; \
-		./$$F.byte$(EXE) > $$F.byte.result; \
-		$(DIFF) $$F.reference $$F.byte.result && echo " => passed" || echo " => failed"; \
+.PHONY: skip
+skip:
+	@for c in bytecode native; do \
+	  echo " ... testing '$$c': => skipped" ; \
 	done
 
+.PHONY: run-byte
+run-byte: common
+	@printf " ... testing 'bytecode':"
+	@$(OCAMLC) $(COMPFLAGS) -c tcallback.ml
+	@$(OCAMLC) $(COMPFLAGS) -o ./program$(EXE) -custom unix.cma \
+	           callbackprim.$(O) tcallback.cmo
+	@./program$(EXE) >bytecode.result
+	@$(DIFF) reference bytecode.result \
+	&& echo " => passed" || echo " => failed"
+
 .PHONY: run-opt
-run-opt:
+run-opt: common
 	@if $(BYTECODE_ONLY); then : ; else \
-		for f in *.ml; do \
-			printf " ... testing 'nativecode':"; \
-			F=`basename $$f .ml`; \
-			$(CC) -c $$F.c; \
-			mv $$F.$(O) $$F.c.$(O); \
-			$(OCAMLOPT) $(COMPFLAGS) -c $$F.mli; \
-			$(OCAMLOPT) $(COMPFLAGS) -o ./$$F.native$(EXE) unix.cmxa $$F.c.$(O) $$F.ml; \
-			./$$F.native$(EXE) > $$F.native.result; \
-			$(DIFF) $$F.reference $$F.native.result && echo " => passed" || echo " => failed"; \
-		done; \
+	  printf " ... testing 'native':"; \
+	  $(OCAMLOPT) $(COMPFLAGS) -c tcallback.ml; \
+	  $(OCAMLOPT) $(COMPFLAGS) -o ./program$(EXE) unix.cmxa \
+	              callbackprim.$(O) tcallback.cmx; \
+	  ./program$(EXE) >native.result; \
+	  $(DIFF) reference native.result \
+	  && echo " => passed" || echo " => failed"; \
 	fi
 
 .PHONY: promote
@@ -58,6 +64,6 @@ promote: defaultpromote
 
 .PHONY: clean
 clean: defaultclean
-	@rm -f *.result *.byte$(EXE) *.native$(EXE)
+	@rm -f *.result ./program$(EXE)
 
 include $(BASEDIR)/makefiles/Makefile.common
diff --git a/testsuite/tests/runtime-errors/Makefile b/testsuite/tests/runtime-errors/Makefile
--- a/testsuite/tests/runtime-errors/Makefile
+++ b/testsuite/tests/runtime-errors/Makefile
@@ -1,21 +1,24 @@
-#########################################################################
-#                                                                       #
-#                                 OCaml                                 #
-#                                                                       #
-#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
-#                                                                       #
-#   Copyright 2010 Institut National de Recherche en Informatique et    #
-#   en Automatique.  All rights reserved.  This file is distributed     #
-#   under the terms of the Q Public License version 1.0.                #
-#                                                                       #
-#########################################################################
+#**************************************************************************
+#*                                                                        *
+#*                                OCaml                                   *
+#*                                                                        *
+#*                 Xavier Clerc, SED, INRIA Rocquencourt                  *
+#*                                                                        *
+#*   Copyright 2010 Institut National de Recherche en Informatique et     *
+#*     en Automatique.                                                    *
+#*                                                                        *
+#*   All rights reserved.  This file is distributed under the terms of    *
+#*   the GNU Lesser General Public License version 2.1, with the          *
+#*   special exception on linking described in the file LICENSE.          *
+#*                                                                        *
+#**************************************************************************
 
 BASEDIR=../..
 
 .PHONY: default
 default:
-	$(MAKE) compile
-	$(MAKE) run
+	@$(MAKE) compile
+	@$(MAKE) run
 
 .PHONY: compile
 compile:
@@ -30,20 +33,39 @@ compile:
 	@grep -q HAS_STACK_OVERFLOW_DETECTION $(TOPDIR)/config/s.h \
 	  || rm -f stackoverflow.native$(EXE)
 
+# Cygwin doesn't allow the stack limit to be changed - the 4096 is
+# intended to be larger than the its default stack size. The logic
+# causes the test to be skipped if the stacksize cannot be brought
+# below this value (uname -s value exits with an error status in Cygwin)
 .PHONY: run
 run:
-	@ulimit -s 1024; \
+	@ul=`ulimit -s`; \
+	 if ( [ "$$ul" = "unlimited" ] || [ $$ul -gt 4096 ] ) ; then \
+	   ulimit -s 1024 && ul=1 || ul=0 ; \
+	 else \
+	   ul=1; \
+	 fi; \
 	 for f in *.bytecode; do \
 	  printf " ... testing '$$f':"; \
-	  $(OCAMLRUN) ./$$f >$$f.result 2>&1 || true; \
-	  DIFF="$(DIFF)" sh $$f.checker \
-	  && echo " => passed" || echo " => failed"; \
-	  fn=`basename $$f bytecode`native; \
-	  if $(BYTECODE_ONLY) || [ ! -f "$${fn}$(EXE)" ] ; then : ; else \
-	    printf " ... testing '$$fn':"; \
-	    ./$${fn}$(EXE) >$$fn.result 2>&1 || true; \
-	    DIFF="$(DIFF)" sh $$fn.checker \
+	  if [ $$ul -eq 1 ] ; then \
+	    $(OCAMLRUN) ./$$f >$$f.result 2>&1 || true; \
+	    DIFF="$(DIFF)" sh $$f.checker \
 	    && echo " => passed" || echo " => failed"; \
+	  else \
+	    echo " => unexpected error"; \
+	  fi; \
+	  fn=`basename $$f bytecode`native; \
+	  if $(BYTECODE_ONLY) || [ ! -f "$${fn}$(EXE)" ] ; then \
+	    echo " ... testing '$$fn': => skipped" ; \
+	  else \
+	    printf " ... testing '$$fn':"; \
+	    if [ $$ul -eq 1 ] ; then \
+	      ./$${fn}$(EXE) >$$fn.result 2>&1 || true; \
+	      DIFF="$(DIFF)" sh $$fn.checker \
+	      && echo " => passed" || echo " => failed"; \
+	    else \
+	      echo " => unexpected error"; \
+	    fi; \
 	  fi; \
 	done
 
