add message when compilation fails
git-svn-id: http://caml.inria.fr/svn/ocaml/version/4.00@12581 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -47,7 +47,7 @@ run-file:
 	  sh `basename $(FILE) ml`runner; \
 	else \
 	  ./program $(PROGRAM_ARGS) > `basename $(FILE) ml`result; \
-	fi
+	fi || (echo " => failed" && exit 1)
 	@if [ -f `basename $(FILE) ml`checker ]; then \
 	  sh `basename $(FILE) ml`checker; \
 	else \
