testsuite: general cleanup of makefiles
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@13648 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/makefiles/Makefile.okbad b/testsuite/makefiles/Makefile.okbad
--- a/testsuite/makefiles/Makefile.okbad
+++ b/testsuite/makefiles/Makefile.okbad
@@ -16,15 +16,18 @@ compile:
 	@for file in *.ml; do \
 	  printf " ... testing '$$file'"; \
 	  if [ `echo $$file | grep bad` ]; then \
-	    if $(OCAMLC) -c -w a $$file 2> /dev/null; then \
-	      echo " => failed" && exit 1; \
-	    else echo " => passed"; \
-	    fi; \
+	    $(OCAMLC) -c -w a $$file 2>/dev/null \
+            && echo " => failed" || echo " => passed"; \
 	  else \
-	    test -f `basename $$file ml`mli && $(OCAMLC) -c -w a `basename $$file ml`mli; \
-	    $(OCAMLC) -c -w a $$file 2> /dev/null || (echo " => failed" && exit 1); \
-	    test -f `basename $$file ml`reference && $(OCAMLC) `basename $$file ml`cmo && ./a.out > `basename $$file ml`result && ($(DIFF) `basename $$file ml`reference `basename $$file ml`result || (echo " => failed" && exit 1)); \
-	    echo " => passed"; \
+	    F="`basename $$file .ml`"; \
+	    test -f $$F.mli && $(OCAMLC) -c -w a $$F.mli; \
+	    $(OCAMLC) -c -w a $$file 2>/dev/null \
+	    && if [ -f $$F.reference ]; then \
+	         $(OCAMLC) $$F.cmo \
+	         && ./a.out >$$F.result \
+	         && $(DIFF) $$F.reference $$F.result >/dev/null; \
+	       fi \
+	    && echo " => passed" || echo " => failed"; \
 	  fi; \
 	done
 
diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -18,14 +18,16 @@ CMA_FILES=$(LIBRARIES:=.cma)
 CMXA_FILES=$(LIBRARIES:=.cmxa)
 O_FILES=$(C_FILES:=.o)
 
-CUSTOM_FLAG=`if [ -z "$(C_FILES)" ]; then true; else echo '-custom'; fi`
+CUSTOM_FLAG=`if [ -n "$(C_FILES)" ]; then echo '-custom'; fi`
 ADD_CFLAGS+=$(CUSTOM_FLAG)
-FORTRAN_LIB=`if [ -z "$(F_FILES)" ]; then true; else echo '$(FORTRAN_LIBRARY)'; fi`
+FORTRAN_LIB=`if [ -n "$(F_FILES)" ]; then echo '$(FORTRAN_LIBRARY)'; fi`
 ADD_CFLAGS+=$(FORTRAN_LIB)
 ADD_OPTFLAGS+=$(FORTRAN_LIB)
 
 check:
-	@if [ -n "$(FORTRAN_COMPILER)" -o -z "$(F_FILES)" ]; then $(MAKE) run-all; fi
+	@if [ -n "$(FORTRAN_COMPILER)" -o -z "$(F_FILES)" ]; then \
+	  $(MAKE) run-all; \
+	fi
 
 run-all:
 	@for file in $(C_FILES); do \
@@ -36,36 +38,38 @@ run-all:
 	done;
 	@for file in *.ml; do \
 	  if [ -f `basename $$file ml`precheck ]; then \
-            CANKILL=$(CANKILL) sh `basename $$file ml`precheck || continue; \
-          fi; \
+	    CANKILL=$(CANKILL) sh `basename $$file ml`precheck || continue; \
+	  fi; \
 	  printf " ... testing '$$file':"; \
-	  $(MAKE) run-file DESC=ocamlc COMP='$(OCAMLC)' COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_CFLAGS) $(O_FILES) -w a $(CMA_FILES) -I $(TTOP)/testsuite/lib $(CMO_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS) && \
-	  if [ -z "$(BYTECODE_ONLY)" ]; then \
-	    $(MAKE) run-file DESC=ocamlopt COMP='$(OCAMLOPT)' COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_OPTFLAGS) $(O_FILES) -w a $(CMXA_FILES) -I $(TTOP)/testsuite/lib $(CMX_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS); \
-	  fi && \
-	  if [ ! -z $(UNSAFE) ]; then \
-	    $(MAKE) run-file DESC=ocamlc-unsafe COMP='$(OCAMLC)' COMPFLAGS='-w a -unsafe -I $(TTOP)/testsuite/lib $(CMO_FILES)' FILE=$$file && \
-	    if [ -z "$(BYTECODE_ONLY)" ]; then \
+	  $(MAKE) run-file DESC=ocamlc COMP='$(OCAMLC)' COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_CFLAGS) $(O_FILES) -w a $(CMA_FILES) -I $(TTOP)/testsuite/lib $(CMO_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS) \
+	  && if [ -z "$(BYTECODE_ONLY)" ]; then \
+	       $(MAKE) run-file DESC=ocamlopt COMP='$(OCAMLOPT)' COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_OPTFLAGS) $(O_FILES) -w a $(CMXA_FILES) -I $(TTOP)/testsuite/lib $(CMX_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS); \
+	     fi \
+	  && if [ ! -z $(UNSAFE) ]; then \
+	       $(MAKE) run-file DESC=ocamlc-unsafe COMP='$(OCAMLC)' COMPFLAGS='-w a -unsafe -I $(TTOP)/testsuite/lib $(CMO_FILES)' FILE=$$file \
+	    && if [ -z "$(BYTECODE_ONLY)" ]; then \
 	      $(MAKE) run-file DESC=ocamlopt-unsafe COMP='$(OCAMLOPT)' COMPFLAGS='-w a -unsafe -I $(TTOP)/testsuite/lib $(CMX_FILES)' FILE=$$file; \
-	    fi; \
-	  fi && \
-	  echo " => passed"; \
-	done;
+	       fi; \
+	     fi \
+	  && echo " => passed" || echo " => failed"; \
+	done
 
 run-file:
 	@printf " $(DESC)"
 	@rm -f program program.exe
 	@$(COMP) $(COMPFLAGS) $(FILE) -o program$(EXE)
-	@if [ -f `basename $(FILE) ml`runner ]; then \
-	  sh `basename $(FILE) ml`runner; \
+	@F="`basename $(FILE) .ml`"; \
+	if [ -f $$F.runner ]; then \
+	  sh $$F.runner; \
 	else \
-	  ./program$(EXE) $(PROGRAM_ARGS) > `basename $(FILE) ml`result; \
-	fi || (echo " => failed" && exit 1)
-	@if [ -f `basename $(FILE) ml`checker ]; then \
-	  DIFF="$(DIFF)" sh `basename $(FILE) ml`checker; \
+	  ./program$(EXE) $(PROGRAM_ARGS) > $$F.result; \
+	fi \
+	&& \
+	if [ -f $$F.checker ]; then \
+	  DIFF="$(DIFF)" sh $$F.checker; \
 	else \
-	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null; \
-	fi || (echo " => failed" && exit 1)
+	  $(DIFF) $$F.reference $$F.result >/dev/null; \
+	fi
 
 promote: defaultpromote
 
diff --git a/testsuite/tests/backtrace/Makefile b/testsuite/tests/backtrace/Makefile
--- a/testsuite/tests/backtrace/Makefile
+++ b/testsuite/tests/backtrace/Makefile
@@ -18,8 +18,11 @@ run-all:
 	  $(OCAMLC) -g -o $(EXECNAME) $$file; \
 	  for arg in a b c d ''; do \
 	    printf " ... testing '$$file' (with argument '$$arg'):"; \
-	    (OCAMLRUNPARAM=b=1 $(EXECNAME) $$arg || true) > `basename $$file ml`$$arg.result 2>&1; \
-	    $(DIFF) `basename $$file ml`$$arg.reference `basename $$file ml`$$arg.result > /dev/null && echo " => passed" || (echo " => failed" && exit 1); \
+	    F="`basename $$file .ml`"; \
+	    (OCAMLRUNPARAM=b=1 $(EXECNAME) $$arg || true) \
+	         >$$F.$$arg.result 2>&1; \
+	    $(DIFF) $$F.$$arg.reference $$F.$$arg.result >/dev/null \
+	    && echo " => passed" || echo " => failed"; \
 	  done; \
 	done
 
diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -26,18 +26,18 @@ run-byte: common
 	@printf " ... testing 'bytecode':"
 	@$(OCAMLC) -c tcallback.ml
 	@$(OCAMLC) -o ./program -custom unix.cma callbackprim.$(O) tcallback.cmo
-	@./program > bytecode.result
-	@$(DIFF) reference bytecode.result || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@./program >bytecode.result
+	@$(DIFF) reference bytecode.result \
+	&& echo " => passed" || echo " => failed"
 
 run-opt: common
 	@if [ -z "$(BYTECODE_ONLY)" ]; then \
 	  printf " ... testing 'native':"; \
 	  $(OCAMLOPT) -c tcallback.ml; \
 	  $(OCAMLOPT) -o ./program unix.cmxa callbackprim.$(O) tcallback.cmx; \
-	  ./program > native.result; \
-	  $(DIFF) reference native.result || (echo " => failed" && exit 1); \
-	  echo " => passed"; \
+	  ./program >native.result; \
+	  $(DIFF) reference native.result \
+	  && echo " => passed" || echo " => failed"; \
 	fi
 
 promote: defaultpromote
diff --git a/testsuite/tests/lib-dynlink-bytecode/Makefile b/testsuite/tests/lib-dynlink-bytecode/Makefile
--- a/testsuite/tests/lib-dynlink-bytecode/Makefile
+++ b/testsuite/tests/lib-dynlink-bytecode/Makefile
@@ -18,7 +18,8 @@ compile:
 	@$(OCAMLC) -c registry.ml
 	@for file in stub*.c; do \
 	  $(OCAMLC) -c $$file; \
-	  $(OCAMLMKLIB) -o `echo $$file | sed -e 's/stub/plug/' | sed -e 's/\.c//'` `basename $$file c`o; \
+	  $(OCAMLMKLIB) -o `echo $$file | sed -e 's/stub/plug/' -e 's/\.c//'` \
+	                `basename $$file c`o; \
 	done
 	@for file in plug*.ml; do \
 	  $(OCAMLC) -c $$file; \
@@ -26,24 +27,26 @@ compile:
 	done
 	@$(OCAMLC) -c main.ml
 	@$(OCAMLC) -o main dynlink.cma registry.cmo main.cmo
-	@$(OCAMLC) -o static -linkall registry.cmo plug1.cma plug2.cma -use-runtime $(PREFIX)/bin/ocamlrun
-	@$(OCAMLC) -o custom -custom -linkall registry.cmo plug2.cma plug1.cma -I .
+	@$(OCAMLC) -o static -linkall registry.cmo plug1.cma plug2.cma \
+	           -use-runtime $(PREFIX)/bin/ocamlrun
+	@$(OCAMLC) -o custom -custom -linkall registry.cmo plug2.cma plug1.cma \
+	           -I .
 
 run:
 	@printf " ... testing 'main'"
-	@export LD_LIBRARY_PATH=`pwd` && ./main plug1.cma plug2.cma > main.result
-	@$(DIFF) main.reference main.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@LD_LIBRARY_PATH="`pwd`" ./main plug1.cma plug2.cma >main.result
+	@$(DIFF) main.reference main.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
 
 	@printf " ... testing 'static'"
-	@export LD_LIBRARY_PATH=`pwd` && ./static > static.result
-	@$(DIFF) static.reference static.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@LD_LIBRARY_PATH="`pwd`" ./static >static.result
+	@$(DIFF) static.reference static.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
 
 	@printf " ... testing 'custom'"
-	@export LD_LIBRARY_PATH=`pwd` && ./custom > custom.result
-	@$(DIFF) custom.reference custom.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@LD_LIBRARY_PATH="`pwd`" ./custom > custom.result
+	@$(DIFF) custom.reference custom.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
 
 promote: defaultpromote
 
diff --git a/testsuite/tests/lib-scanf-2/Makefile b/testsuite/tests/lib-scanf-2/Makefile
--- a/testsuite/tests/lib-scanf-2/Makefile
+++ b/testsuite/tests/lib-scanf-2/Makefile
@@ -25,14 +25,14 @@ compile: tscanf2_io.cmo
 
 run:
 	@printf " ... testing with ocamlc"
-	@./master.byte "`$(CYGPATH) ./slave.byte`" > result.byte 2>&1
-	@$(DIFF) reference result.byte > /dev/null || (echo " => failed" && exit 1)
-	@if [ -z "$(BYTECODE_ONLY)" ]; then \
-	  printf " ocamlopt" && \
-	  ./master.native "`$(CYGPATH) ./slave.native`" > result.native 2>&1 && \
-	  $(DIFF) reference result.native > /dev/null || (echo " => failed" && exit 1) \
-	fi
-	@echo " => passed"
+	@./master.byte "`$(CYGPATH) ./slave.byte`" >result.byte 2>&1
+	@$(DIFF) reference result.byte >/dev/null \
+	&& if [ -z "$(BYTECODE_ONLY)" ]; then \
+	     printf " ocamlopt"; \
+	     ./master.native "`$(CYGPATH) ./slave.native`" >result.native 2>&1;\
+	     $(DIFF) reference result.native >/dev/null; \
+	   fi \
+	&& echo " => passed" || echo " => failed"
 
 promote:
 	@cp result.byte reference
diff --git a/testsuite/tests/tool-ocaml/Makefile b/testsuite/tests/tool-ocaml/Makefile
--- a/testsuite/tests/tool-ocaml/Makefile
+++ b/testsuite/tests/tool-ocaml/Makefile
@@ -17,9 +17,11 @@ compile: lib.cmo
 	@for file in t*.ml; do \
 	  printf " ... testing '$$file'"; \
 	  if [ `echo $(SHOULD_FAIL) | grep $$file` ]; then \
-	    $(OCAML) -w a lib.cmo $$file 2> /dev/null && (echo " => failed" && exit 1) || echo " => passed"; \
+	    $(OCAML) -w a lib.cmo $$file 2>/dev/null \
+	    && echo " => failed" || echo " => passed"; \
 	  else \
-	    $(OCAML) -w a lib.cmo $$file 2> /dev/null && echo " => passed" || (echo " => failed" && exit 1); \
+	    $(OCAML) -w a lib.cmo $$file 2>/dev/null \
+	    && echo " => passed" || echo " => failed"; \
 	  fi; \
 	done
 
