detabisation
git-svn-id: http://caml.inria.fr/svn/ocaml/trunk@5029 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/camlp4/config/configure_batch b/camlp4/config/configure_batch
--- a/camlp4/config/configure_batch
+++ b/camlp4/config/configure_batch
@@ -58,10 +58,10 @@ touch Makefile.cnf
 
 for i in utils parsing otherlibs/dynlink; do
     if test ! -d "$ocaml_top/$i"; then
-	echo "Bad value $ocaml_top for option -ocaml-top"
+        echo "Bad value $ocaml_top for option -ocaml-top"
         echo "There is no directory $ocaml_top/$i"
-	echo "Configuration script failed"
-	exit 1
+        echo "Configuration script failed"
+        exit 1
     fi
 done
 
