avoid diff options that are not available on BSD
git-svn-id: http://caml.inria.fr/svn/ocaml/version/4.00@13576 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/testsuite/tests/tool-ocamldoc/Makefile b/testsuite/tests/tool-ocamldoc/Makefile
--- a/testsuite/tests/tool-ocamldoc/Makefile
+++ b/testsuite/tests/tool-ocamldoc/Makefile
@@ -2,14 +2,11 @@ BASEDIR=../..
 CUSTOM_MODULE=odoc_test
 ADD_COMPFLAGS=-I +ocamldoc
 
-DIFF_OPT=--strip-trailing-cr
-#DIFF_OPT=-b
-
 run: $(CUSTOM_MODULE).cmo
 	@for file in t*.ml; do \
 	  printf " ... testing '$$file'"; \
 	  $(OCAMLDOC) -hide-warnings -g $(CUSTOM_MODULE).cmo -o `basename $$file ml`result $$file; \
-	  $(DIFF) $(DIFF_OPT) `basename $$file ml`reference `basename $$file ml`result > /dev/null && echo " => passed" || (echo " => failed" && exit 1); \
+	  tr -d '\r' < `basename $$file ml`result | $(DIFF) `basename $$file ml`reference - > /dev/null && echo " => passed" || (echo " => failed" && exit 1); \
 	done;
 	@$(OCAMLDOC) -hide-warnings -html t*.ml 2>&1 | grep -v test_types_display || true
 	@$(OCAMLDOC) -hide-warnings -latex t*.ml 2>&1 | grep -v test_types_display || true
