Temporary fix for output-obj test: 1. fix silent failure mode 2. disable the test

diff --git a/testsuite/tests/output_obj/Makefile.disabled b/testsuite/tests/output_obj/Makefile.disabled
--- a/testsuite/tests/output_obj/Makefile.disabled
+++ b/testsuite/tests/output_obj/Makefile.disabled
@@ -16,35 +16,36 @@
 BASEDIR=../..
 SHOULD_FAIL=
 
+
 compile:
 	@for file in *.ml; do \
-	  printf " ... testing native '$$file'"; \
+	  printf " ... testing '$$file' with native"; \
           if $(BYTECODE_ONLY); then \
 	    echo " => skipped"; \
 	  else \
 	    rm -f log $${file}.exe.$(O) $${file}_stub$(EXE); \
-	    ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) \
-                          $${file} >> log 2>&1 && \
+	    ( set -x; \
+	      $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) \
+                          $${file} && \
 	      $(MKEXE) -I$(CTOPDIR)/byterun -o $${file}_stub$(EXE) \
-                       $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c \
-                       >> log 2>&1 && \
-	      ./$${file}_stub$(EXE) >> log 2>&1 && \
-	      echo " => passed") || (echo " => failed" && cat log) ; \
+                       $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c && \
+	      ./$${file}_stub$(EXE) ) > log 2>&1 \
+            && echo " => passed" || (echo " => failed" && cat log); \
 	  fi \
 	done
 	@for file in *.ml; do \
-	  printf " ... testing byte '$$file'"; \
+	  printf " ... testing '$$file' with byte"; \
 	  if [ $(TOOLCHAIN) = msvc ]; then \
 	    echo " => skipped"; \
 	  else \
             rm -f log $${file}.bc.$(O) $${file}_bc_stub$(EXE); \
-	    ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj\
-                        -o $${file}.bc.$(O) $${file} >> log 2>&1 && \
+	    ( set -x; \
+	      $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj\
+                        -o $${file}.bc.$(O) $${file} && \
 	      $(MKEXE) -I$(CTOPDIR)/byterun -o $${file}_bc_stub$(EXE) \
-                       $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c \
-                       >> log 2>&1 && \
-	      ./$${file}_bc_stub$(EXE) >> log 2>&1 && \
-	      echo " => passed") || (echo " => failed" && cat log); \
+                       $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c && \
+	      ./$${file}_bc_stub$(EXE) ) > log 2>&1 \
+	    && echo " => passed" || (echo " => failed" && cat log); \
 	  fi; \
 	done
 	@rm -f log
