Fix output-complete-obj for MSVC:
- bug in ccomp.ml
- bug in test Makefile
- disable testing bytecode on MSVC: AFAICT this never worked.

diff --git a/testsuite/tests/output_obj/Makefile b/testsuite/tests/output_obj/Makefile
--- a/testsuite/tests/output_obj/Makefile
+++ b/testsuite/tests/output_obj/Makefile
@@ -19,23 +19,33 @@ SHOULD_FAIL=
 compile:
 	@for file in *.ml; do \
 	  printf " ... testing native '$$file'"; \
-         if $(BYTECODE_ONLY); then \
-	  echo " => skipped"; \
-	 else \
+          if $(BYTECODE_ONLY); then \
+	    echo " => skipped"; \
+	  else \
 	    rm -f log $${file}.exe.$(O) $${file}_stub$(EXE); \
-	    ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) $${file} >> log 2>&1 && \
-	      $(MKEXE) -I$(CTOPDIR)/byterun $(OUTPUTEXE)$${file}_stub$(EXE) $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c >> log 2>&1 && \
+	    ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) \
+                          $${file} >> log 2>&1 && \
+	      $(MKEXE) -I$(CTOPDIR)/byterun -o $${file}_stub$(EXE) \
+                       $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c \
+                       >> log 2>&1 && \
 	      ./$${file}_stub$(EXE) >> log 2>&1 && \
 	      echo " => passed") || (echo " => failed" && cat log) ; \
-	 fi \
+	  fi \
 	done
 	@for file in *.ml; do \
 	  printf " ... testing byte '$$file'"; \
-          rm -f log $${file}.bc.$(O) $${file}_bc_stub$(EXE); \
-	  ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj -o $${file}.bc.$(O) $${file} >> log 2>&1 && \
-	    $(MKEXE) -I$(CTOPDIR)/byterun $(OUTPUTEXE)$${file}_bc_stub$(EXE) $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c >> log 2>&1 && \
-	    ./$${file}_bc_stub$(EXE) >> log 2>&1 && \
-	    echo " => passed") || (echo " => failed" && cat log); \
+	  if [ $(TOOLCHAIN) = msvc ]; then \
+	    echo " => skipped"; \
+	  else \
+            rm -f log $${file}.bc.$(O) $${file}_bc_stub$(EXE); \
+	    ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj\
+                        -o $${file}.bc.$(O) $${file} >> log 2>&1 && \
+	      $(MKEXE) -I$(CTOPDIR)/byterun -o $${file}_bc_stub$(EXE) \
+                       $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c \
+                       >> log 2>&1 && \
+	      ./$${file}_bc_stub$(EXE) >> log 2>&1 && \
+	      echo " => passed") || (echo " => failed" && cat log); \
+	  fi; \
 	done
 	@rm -f log
 
