[Tests] Print message in case of errors
        for output_obj tests

diff --git a/testsuite/tests/output_obj/Makefile b/testsuite/tests/output_obj/Makefile
--- a/testsuite/tests/output_obj/Makefile
+++ b/testsuite/tests/output_obj/Makefile
@@ -19,18 +19,21 @@ SHOULD_FAIL=
 compile:
 	@for file in *.ml; do \
 	  printf " ... testing native '$$file'"; \
-	  ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.o $${file} 2>/dev/null && \
-	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_stub $${file}.exe.o -lm -ldl $${file}_stub.c 2>/dev/null && \
-	    ./$${file}_stub 1>/dev/null 2>/dev/null && \
-	    echo " => passed" ) || echo " => failed"; \
+	  rm -f log; \
+	  ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.o $${file} >> log 2>&1 && \
+	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_stub $${file}.exe.o -lm -ldl $${file}_stub.c >> log 2>&1 && \
+	    ./$${file}_stub >> log 2>&1 && \
+	    echo " => passed") || (echo " => failed" && cat log) ; \
 	done
 	@for file in *.ml; do \
 	  printf " ... testing byte '$$file'"; \
-	  ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj -o $${file}.bc.o $${file} 2>/dev/null && \
-	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_bc_stub $${file}.bc.o -lm -ldl -lcurses $${file}_stub.c 2>/dev/null && \
-	    ./$${file}_bc_stub 1>/dev/null 2>/dev/null && \
-	    echo " => passed" ) || echo " => failed"; \
+          rm -f log; \
+	  ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj -o $${file}.bc.o $${file} >> log 2>&1 && \
+	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_bc_stub $${file}.bc.o -lm -ldl -lcurses $${file}_stub.c >> log 2>&1 && \
+	    ./$${file}_bc_stub >> log 2>&1 && \
+	    echo " => passed") || (echo " => failed" && cat log); \
 	done
+	@rm -f log
 
 promote:
 
