[Tests] try to fix output-obj tests on windows

diff --git a/testsuite/tests/output_obj/Makefile b/testsuite/tests/output_obj/Makefile
--- a/testsuite/tests/output_obj/Makefile
+++ b/testsuite/tests/output_obj/Makefile
@@ -19,18 +19,22 @@ SHOULD_FAIL=
 compile:
 	@for file in *.ml; do \
 	  printf " ... testing native '$$file'"; \
-	  rm -f log; \
-	  ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) $${file} >> log 2>&1 && \
-	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_stub $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c >> log 2>&1 && \
-	    ./$${file}_stub >> log 2>&1 && \
-	    echo " => passed") || (echo " => failed" && cat log) ; \
+         if $(BYTECODE_ONLY); then \
+	  echo " => skipped"; \
+	 else \
+	    rm -f log; \
+	    ( $(OCAMLOPT) -w a -output-complete-obj -o $${file}.exe.$(O) $${file} >> log 2>&1 && \
+	      $(MKEXE) -I$(CTOPDIR)/byterun $(OUTPUTEXE)$${file}_stub$(EXE) $${file}.exe.$(O) $(NATIVECCLIBS) $${file}_stub.c >> log 2>&1 && \
+	      ./$${file}_stub$(EXE) >> log 2>&1 && \
+	      echo " => passed") || (echo " => failed" && cat log) ; \
+	 fi \
 	done
 	@for file in *.ml; do \
 	  printf " ... testing byte '$$file'"; \
           rm -f log; \
 	  ( $(OCAMLC) -ccopt "-I$(CTOPDIR)/byterun" -w a -output-complete-obj -o $${file}.bc.$(O) $${file} >> log 2>&1 && \
-	    $(CC) $(CFLAGS) $(CPPFLAGS) -I$(CTOPDIR)/byterun -o $${file}_bc_stub $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c >> log 2>&1 && \
-	    ./$${file}_bc_stub >> log 2>&1 && \
+	    $(MKEXE) -I$(CTOPDIR)/byterun $(OUTPUTEXE)$${file}_bc_stub$(EXE) $${file}.bc.$(O) $(BYTECCLIBS) $${file}_stub.c >> log 2>&1 && \
+	    ./$${file}_bc_stub$(EXE) >> log 2>&1 && \
 	    echo " => passed") || (echo " => failed" && cat log); \
 	done
 	@rm -f log
