Fix tests/lib-marshal-closure build and run.

diff --git a/testsuite/tests/lib-marshal-closure/Makefile b/testsuite/tests/lib-marshal-closure/Makefile
--- a/testsuite/tests/lib-marshal-closure/Makefile
+++ b/testsuite/tests/lib-marshal-closure/Makefile
@@ -10,35 +10,58 @@
 #                                                                       #
 #########################################################################
 
-BINARIES := write32.byte write32.native read32.byte read32.native \
-	    write64.byte write64.native read64.byte read64.native
+BYTECODE_EXES := write32.byte read32.byte write32.cbyte read32.cbyte	\
+		 write64.byte read64.byte write64.cbyte read64.cbyte
+NATIVE_EXES := write32.native read32.native write64.native read64.native
+EXES := $(BYTECODE_EXES) $(NATIVE_EXES)
+
+BYTECODE_RUNS := run-32.byte run-32.cbyte run-64.byte run-64.cbyte
+NATIVE_RUNS := run-32.native run-64.native
 
 BASEDIR=../..
 
 .PHONY: default
 default:
-	rm -f $(BINARIES)
+	@$(MAKE) clean
 	@$(MAKE) compile
 	@$(MAKE) run
 
+###
+
 .PHONY: compile
-compile: $(BINARIES)
+compile:
+	@if $(NATIVECODE_ONLY); then : ; else $(MAKE) $(BYTECODE_EXES); fi
+	@if $(BYTECODE_ONLY); then : ; else $(MAKE) $(NATIVE_EXES); fi
+
+%.byte: %.ml
+	@$(OCAMLC) $< -o $@
+
+%.cbyte: %.ml
+	@$(OCAMLC) $< -custom -o $@
+
+%.native: %.ml
+	@$(OCAMLOPT) $< -o $@
+
+###
 
 .PHONY: run
 run:
-	@for arch in 32 64; do						\
-	  for kind in byte native; do					\
-	    echo -n  " ... testing 'arch-$$arch/$$kind'";		\
-	    rm -f data;                             			\
-	    ./write$$arch.$$kind                 			\
-	      > write$$arch$$kind.out 2> write$$arch$$kind.err		\
-	      || exit 1;						\
-	    ./read$$arch.$$kind	                                       	\
-	      > read$$arch$$kind.out 2> read$$arch$$kind.err		\
-	      && ( echo " => passed" )					\
-	      || ( echo " => failed" )					\
-	  done;								\
-	done
+	@if $(NATIVECODE_ONLY); then : ; else $(MAKE) $(BYTECODE_RUNS); fi
+	@if $(BYTECODE_ONLY); then : ; else $(MAKE) $(NATIVE_RUNS); fi
+
+run-%.byte:
+	@printf " ... testing '$*.byte'"
+	@rm -f data
+	@$(OCAMLRUN) ./write$*.byte > write$*.byte.out 2> write$*.byte.err
+	@$(OCAMLRUN) ./read$*.byte > read$*.byte.out 2> read$*.byte.err	\
+	  && echo " => passed" || echo " => failed"
+
+run-%:
+	@printf " ... testing '$*'"
+	@rm -f data
+	@./write$* > write$*.out 2> write$*.err
+	@./read$* > read$*.out 2> read$*.err \
+	  && echo " => passed" || echo " => failed"
 
 ###
 
@@ -47,15 +70,7 @@ promote: defaultpromote
 
 .PHONY: clean
 clean: defaultclean
-	@rm -f data *.byte *.native *.out *.err
-
-###
-
-%.byte: %.ml
-	@$(OCAMLC) $< -custom -o $@
-
-%.native: %.ml
-	@$(OCAMLOPT) $< -o $@
+	@rm -f data *.byte *.cbyte *.native *.out *.err
 
 ###
 
