petites ameliorations
git-svn-id: http://caml.inria.fr/svn/ocaml/version/3.10@8791 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/tools/make-package-macosx b/tools/make-package-macosx
--- a/tools/make-package-macosx
+++ b/tools/make-package-macosx
@@ -101,7 +101,7 @@ mkdir -p resources
 #                                         stop here -> |
 cat >resources/ReadMe.txt <<EOF
 This package installs Objective Caml version ${VERSION}.
-You need Mac OS X 10.5.x (Jaguar), with X11 and the
+You need Mac OS X 10.5.x (Leopard), with X11 and the
 XCode tools (v3.x) installed.
 
 Files will be installed in the following directories:
@@ -123,20 +123,21 @@ size=`expr $size + 8192`
 
 hdiutil create -sectors $size ocaml-rw.dmg
 name=`hdid -nomount ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
-newfs_hfs -v 'Objective Caml' $name
+volname="Objective Caml ${VERSION}"
+newfs_hfs -v "$volname" $name
 hdiutil detach $name
 
 name=`hdid ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
-if test -d '/Volumes/Objective Caml'; then
-  ditto -rsrcFork ocaml.pkg "/Volumes/Objective Caml/ocaml.pkg"
-  cp resources/ReadMe.txt "/Volumes/Objective Caml/"
+if test -d "/Volumes/$volname"; then
+  ditto -rsrcFork ocaml.pkg "/Volumes/$volname/ocaml.pkg"
+  cp resources/ReadMe.txt "/Volumes/$volname/"
 else
-  echo 'Unable to mount the disk image as "/Volumes/Objective Caml"' >&2
+  echo "Unable to mount the disk image as \"/Volumes/$volname\"" >&2
   exit 3
 fi
-open "/Volumes/Objective Caml"
+open "/Volumes/$volname"
+sleep 2
 hdiutil detach $name
-sleep 2  # give the Finder time to remove the icon from the Desktop
 
 rm -rf "ocaml-${VERSION}.dmg"
 hdiutil convert ocaml-rw.dmg -format UDZO -o "ocaml-${VERSION}.dmg"
