Merge from diff ocaml3100/ocaml3102: cvs update -j ocaml3100 -j ocaml3102 -kk
git-svn-id: http://caml.inria.fr/svn/ocaml/branches/cducetrunk@8864 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/tools/make-package-macosx b/tools/make-package-macosx
--- a/tools/make-package-macosx
+++ b/tools/make-package-macosx
@@ -18,8 +18,8 @@ cd package-macosx
 rm -rf ocaml.pkg ocaml-rw.dmg
 
 VERSION=`head -1 ../VERSION`
-VERSION_MAJOR=`sed -n -e '1s/^\([0-9]*\)\..*/\1/p' ../VERSION
-VERSION_MINOR=`sed -n -e '1s/^[0-9]*\.\([0-9]*\)[.+].*/\1/p' ../VERSION
+VERSION_MAJOR=`sed -n -e '1s/^\([0-9]*\)\..*/\1/p' ../VERSION`
+VERSION_MINOR=`sed -n -e '1s/^[0-9]*\.\([0-9]*\)[.+].*/\1/p' ../VERSION`
 
 # Worked in 10.2:
 
@@ -101,8 +101,8 @@ mkdir -p resources
 #                                         stop here -> |
 cat >resources/ReadMe.txt <<EOF
 This package installs Objective Caml version ${VERSION}.
-You need Mac OS X 10.4.x (Tiger), with X11 and the
-XCode tools (v2.4) installed.
+You need Mac OS X 10.5.x (Leopard), with X11 and the
+XCode tools (v3.x) installed.
 
 Files will be installed in the following directories:
 
@@ -112,7 +112,7 @@ Files will be installed in the following directories:
 EOF
 
 chmod -R g-w root
-sudo chown -R root:admin root
+sudo chown -R root:wheel root
 
 /Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker \
   -build -p "`pwd`/ocaml.pkg" -f "`pwd`/root" -i "`pwd`/Info.plist" \
@@ -123,18 +123,20 @@ size=`expr $size + 8192`
 
 hdiutil create -sectors $size ocaml-rw.dmg
 name=`hdid -nomount ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
-newfs_hfs -v 'Objective Caml' $name
+volname="Objective Caml ${VERSION}"
+newfs_hfs -v "$volname" $name
 hdiutil detach $name
 
 name=`hdid ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
-if test -d '/Volumes/Objective Caml'; then
-  ditto -rsrcFork ocaml.pkg "/Volumes/Objective Caml/ocaml.pkg"
-  cp resources/ReadMe.txt "/Volumes/Objective Caml/"
+if test -d "/Volumes/$volname"; then
+  ditto -rsrcFork ocaml.pkg "/Volumes/$volname/ocaml.pkg"
+  cp resources/ReadMe.txt "/Volumes/$volname/"
 else
-  echo 'Unable to mount the disk image as "/Volumes/Objective Caml"' >&2
+  echo "Unable to mount the disk image as \"/Volumes/$volname\"" >&2
   exit 3
 fi
-open "/Volumes/Objective Caml"
+open "/Volumes/$volname"
+sleep 2
 hdiutil detach $name
 
 rm -rf "ocaml-${VERSION}.dmg"
