Allow tools/unlabel to run from anywhere

diff --git a/tools/unlabel b/tools/unlabel
--- a/tools/unlabel
+++ b/tools/unlabel
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #**************************************************************************
 #*                                                                        *
 #*                                 OCaml                                  *
@@ -18,78 +18,85 @@
 #an alphabetic character or ( or '. This should avoid altering the contents of
 #comments.
 
+cd $(dirname "$0")/..
+
+if [[ ! -d stdlib || ! -d otherlibs ]] ; then
+  echo 'Cannot find the stdlib and otherlibs directories' >&2
+  exit 1
+fi
+
 #Stdlib
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/listLabels.mli > ../stdlib/list.mli
+  stdlib/listLabels.mli > stdlib/list.mli
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/arrayLabels.mli > ../stdlib/array.mli
+  stdlib/arrayLabels.mli > stdlib/array.mli
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/stringLabels.mli > ../stdlib/string.mli
+  stdlib/stringLabels.mli > stdlib/string.mli
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/bytesLabels.mli > ../stdlib/bytes.mli
+  stdlib/bytesLabels.mli > stdlib/bytes.mli
 
 #Stdlib - MoreLabels
 
 #The unlabeling
 #Two (slightly different) rounds required to deal with f:(key:key
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/templates/hashtbl.template.mli > ../stdlib/hashtbl.temp.mli
+  stdlib/templates/hashtbl.template.mli > stdlib/hashtbl.temp.mli
 perl -p -e "s/\([a-z_]+:([a-z\('])/\(\1/g" \
-  ../stdlib/hashtbl.temp.mli > ../stdlib/hashtbl.mli
-rm -f ../stdlib/hashtbl.temp.mli
+  stdlib/hashtbl.temp.mli > stdlib/hashtbl.mli
+rm -f stdlib/hashtbl.temp.mli
 
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/templates/map.template.mli > ../stdlib/map.temp.mli
+  stdlib/templates/map.template.mli > stdlib/map.temp.mli
 perl -p -e "s/\([a-z_]+:([a-z\('])/\(\1/g" \
-  ../stdlib/map.temp.mli > ../stdlib/map.mli
-rm -f ../stdlib/map.temp.mli
+  stdlib/map.temp.mli > stdlib/map.mli
+rm -f stdlib/map.temp.mli
 
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../stdlib/templates/set.template.mli > ../stdlib/set.temp.mli
+  stdlib/templates/set.template.mli > stdlib/set.temp.mli
 perl -p -e "s/\([a-z_]+:([a-z\('])/\(\1/g" \
-  ../stdlib/set.temp.mli > ../stdlib/set.mli
-rm -f ../stdlib/set.temp.mli
+  stdlib/set.temp.mli > stdlib/set.mli
+rm -f stdlib/set.temp.mli
 
 #Substitute the labeled modules in to moreLabels.mli
 perl -p -e\
-  's/HASHTBL/`tail -n +19 ..\/stdlib\/templates\/hashtbl.template.mli`/e' \
-  ../stdlib/templates/moreLabels.template.mli > ../stdlib/moreLabels.temp.mli
-perl -p -e 's/MAP/`tail -n +19 ..\/stdlib\/templates\/map.template.mli`/e' \
-  ../stdlib/moreLabels.temp.mli > ../stdlib/moreLabels.temp2.mli
-perl -p -e 's/SET/`tail -n +19 ..\/stdlib\/templates\/set.template.mli`/e' \
-  ../stdlib/moreLabels.temp2.mli > ../stdlib/moreLabels.mli
-rm -f ../stdlib/moreLabels.temp.mli ../stdlib/moreLabels.temp2.mli
+  's/HASHTBL/`tail -n +19 stdlib\/templates\/hashtbl.template.mli`/e' \
+  stdlib/templates/moreLabels.template.mli > stdlib/moreLabels.temp.mli
+perl -p -e 's/MAP/`tail -n +19 stdlib\/templates\/map.template.mli`/e' \
+  stdlib/moreLabels.temp.mli > stdlib/moreLabels.temp2.mli
+perl -p -e 's/SET/`tail -n +19 stdlib\/templates\/set.template.mli`/e' \
+  stdlib/moreLabels.temp2.mli > stdlib/moreLabels.mli
+rm -f stdlib/moreLabels.temp.mli stdlib/moreLabels.temp2.mli
 
 #Fix up
 perl -p -e "s/type statistics =/type statistics = Hashtbl\.statistics =/" \
-  ../stdlib/moreLabels.mli > ../stdlib/moreLabels.temp.mli
+  stdlib/moreLabels.mli > stdlib/moreLabels.temp.mli
 perl -p -e "s/type \('a, 'b\) t/type \('a, 'b\) t = \('a, 'b) Hashtbl.t/" \
-  ../stdlib/moreLabels.temp.mli > ../stdlib/moreLabels.temp2.mli
+  stdlib/moreLabels.temp.mli > stdlib/moreLabels.temp2.mli
 perl -p -e\
   "s/module Make \(H : HashedType\) : S with type key = H.t\
-/`cat unlabel-patches/1.mli`/" \
-  ../stdlib/moreLabels.temp2.mli > ../stdlib/moreLabels.temp3.mli
+/`cat tools/unlabel-patches/1.mli`/" \
+  stdlib/moreLabels.temp2.mli > stdlib/moreLabels.temp3.mli
 perl -p -e\
   "s/module MakeSeeded \(H : SeededHashedType\) : SeededS with type key = H.t\
-/`cat unlabel-patches/2.mli`/" \
-  ../stdlib/moreLabels.temp3.mli > ../stdlib/moreLabels.temp4.mli
+/`cat tools/unlabel-patches/2.mli`/" \
+  stdlib/moreLabels.temp3.mli > stdlib/moreLabels.temp4.mli
 perl -p -e\
   "s/module Make \(Ord : OrderedType\) : S with type key = Ord.t\
-/`cat unlabel-patches/3.mli`/" \
-  ../stdlib/moreLabels.temp4.mli > ../stdlib/moreLabels.temp5.mli
+/`cat tools/unlabel-patches/3.mli`/" \
+  stdlib/moreLabels.temp4.mli > stdlib/moreLabels.temp5.mli
 perl -p -e\
   "s/module Make \(Ord : OrderedType\) : S with type elt = Ord.t\
-/`cat unlabel-patches/4.mli`/" \
-  ../stdlib/moreLabels.temp5.mli > ../stdlib/moreLabels.mli
-rm -f ../stdlib/moreLabels.temp.mli
-rm -f ../stdlib/moreLabels.temp2.mli
-rm -f ../stdlib/moreLabels.temp3.mli
-rm -f ../stdlib/moreLabels.temp4.mli
-rm -f ../stdlib/moreLabels.temp5.mli
+/`cat tools/unlabel-patches/4.mli`/" \
+  stdlib/moreLabels.temp5.mli > stdlib/moreLabels.mli
+rm -f stdlib/moreLabels.temp.mli
+rm -f stdlib/moreLabels.temp2.mli
+rm -f stdlib/moreLabels.temp3.mli
+rm -f stdlib/moreLabels.temp4.mli
+rm -f stdlib/moreLabels.temp5.mli
 
 #Unix
 perl -p -e "s/ [a-z_]+:([a-z\('])/ \1/g" \
-  ../otherlibs/unix/unixLabels.mli > ../otherlibs/unix/unix.mli
+  otherlibs/unix/unixLabels.mli > otherlibs/unix/unix.mli
 
 #Remove type equivalences from unix.mli
 
@@ -140,7 +147,7 @@ for typ in "${arr[@]}"
 do
     export typ
     tmpfile=$(mktemp)
-    perl -p -e 's/ = Unix.$ENV{'typ'}//' ../otherlibs/unix/unix.mli > ${tmpfile}
-    cat ${tmpfile} > ../otherlibs/unix/unix.mli
+    perl -p -e 's/ = Unix.$ENV{'typ'}//' otherlibs/unix/unix.mli > ${tmpfile}
+    cat ${tmpfile} > otherlibs/unix/unix.mli
     rm -f ${tmpfile}
 done
