Merge with ocaml trunk 12778 -> 13774
git-svn-id: http://caml.inria.fr/svn/ocaml/branches/jocamltrunk@14456 f963ae5c-01c2-4b8c-9fe0-0dff7051ff02

diff --git a/asmrun/Makefile b/asmrun/Makefile
--- a/asmrun/Makefile
+++ b/asmrun/Makefile
@@ -11,8 +11,6 @@
 #                                                                       #
 #########################################################################
 
-# $Id: Makefile 12959 2012-09-27 13:12:51Z maranget $
-
 include ../config/Makefile
 
 CC=$(NATIVECC)
@@ -172,8 +170,11 @@ clean::
 .SUFFIXES: .S .d.o .p.o
 
 .S.o:
-	$(ASPP) -DSYS_$(SYSTEM) -o $*.o $*.S || \
-	{ echo "If your assembler produced syntax errors, it is probably unhappy with the"; echo "preprocessor. Check your assembler, or try producing $*.o by hand."; exit 2; }
+	$(ASPP) -DSYS_$(SYSTEM) -DMODEL_$(MODEL) -o $*.o $*.S || \
+	{ echo "If your assembler produced syntax errors, it is probably";\
+          echo "unhappy with the preprocessor. Check your assembler, or";\
+          echo "try producing $*.o by hand.";\
+          exit 2; }
 
 .S.p.o:
 	$(ASPP) -DSYS_$(SYSTEM) $(ASPPPROFFLAGS) -o $*.p.o $*.S
diff --git a/testsuite/Makefile b/testsuite/Makefile
--- a/testsuite/Makefile
+++ b/testsuite/Makefile
@@ -1,37 +1,64 @@
-# $Id: Makefile 12858 2012-08-10 14:45:51Z maranget $
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
+
 
 BASEDIR=${PWD}
-NO_PRINT=`($(MAKE) empty --no-print-directory > /dev/null 2>&1) && echo '--no-print-directory' || echo ''`
+NO_PRINT=`$(MAKE) empty --no-print-directory >/dev/null 2>&1 && echo '--no-print-directory'`
 
+FIND=find
+include ../config/Makefile
+
+.PHONY: default
 default:
 	@echo "Available targets:"
-	@echo "  all             launches all tests"
-	@echo "  list FILE=f     launches the tests referenced in file f (one path per line)"
-	@echo "  one DIR=p       launches the tests located in path p"
-	@echo "  promote DIR=p   promotes the reference files for the tests located in path p"
-	@echo "  lib             builds library modules"
-	@echo "  clean           deletes generated files"
-	@echo "  report          prints the report for the last execution, if any"
+	@echo "  all             launch all tests"
+	@echo "  list FILE=f     launch the tests referenced in file f (one path per line)"
+	@echo "  one DIR=p       launch the tests located in path p"
+	@echo "  promote DIR=p   promote the reference files for the tests located in path p"
+	@echo "  lib             build library modules"
+	@echo "  clean           delete generated files"
+	@echo "  report          print the report for the last execution, if any"
 
+.PHONY: all
 all: lib
 	@for dir in tests/*; do \
 	  $(MAKE) $(NO_PRINT) exec-one DIR=$$dir; \
 	done 2>&1 | tee _log
 	@$(MAKE) report
 
+.PHONY: list
 list: lib
-	@if [ -z $(FILE) ]; then echo "No value set for variable 'FILE'."; exit 1; fi
-	@if [ ! -f $(FILE) ]; then echo "File '$(FILE)' does not exist."; exit 1; fi
+	@if [ -z "$(FILE)" ]; \
+	  then echo "No value set for variable 'FILE'."; \
+	  exit 1; \
+	fi
 	@while read LINE; do \
 	  $(MAKE) $(NO_PRINT) exec-one DIR=$$LINE; \
-	done < $(FILE) 2>&1 | tee _log
+	done <$(FILE) 2>&1 | tee _log
 	@$(MAKE) report
 
+.PHONY: one
 one: lib
-	@if [ -z $(DIR) ]; then echo "No value set for variable 'DIR'."; exit 1; fi
-	@if [ ! -d $(DIR) ]; then echo "Directory '$(DIR)' does not exist."; exit 1; fi
+	@if [ -z "$(DIR)" ]; then \
+	  echo "No value set for variable 'DIR'."; \
+	  exit 1; \
+	fi
+	@if [ ! -d $(DIR) ]; then \
+	  echo "Directory '$(DIR)' does not exist."; \
+	  exit 1; \
+	fi
 	@$(MAKE) $(NO_PRINT) exec-one DIR=$(DIR)
 
+.PHONY: exec-one
 exec-one:
 	@if [ ! -f $(DIR)/Makefile ]; then \
 	  for dir in $(DIR)/*; do \
@@ -39,35 +66,39 @@ exec-one:
 	      $(MAKE) exec-one DIR=$$dir; \
 	    fi; \
 	  done; \
-        else \
+	else \
 	  echo "Running tests from '$$DIR' ..."; \
-	  (cd $(DIR) && $(MAKE) TERM=dumb BASEDIR=$(BASEDIR)); \
+	  cd $(DIR) && \
+	  $(MAKE) TERM=dumb BASEDIR=$(BASEDIR) || echo '=> unexpected error'; \
 	fi
 
-promote: FORCE
-	@if [ -z $(DIR) ]; then echo "No value set for variable 'DIR'."; exit 1; fi
-	@if [ ! -d $(DIR) ]; then echo "Directory '$(DIR)' does not exist."; exit 1; fi
-	@(cd $(DIR) && $(MAKE) TERM=dumb BASEDIR=$(BASEDIR) promote)
+.PHONY: promote
+promote:
+	@if [ -z "$(DIR)" ]; then \
+	  echo "No value set for variable 'DIR'."; \
+	  exit 1; \
+	fi
+	@if [ ! -d $(DIR) ]; then \
+	  echo "Directory '$(DIR)' does not exist."; \
+	  exit 1; \
+	fi
+	@cd $(DIR) && $(MAKE) TERM=dumb BASEDIR=$(BASEDIR) promote
 
-lib: FORCE
-	@(cd lib && $(MAKE) -s BASEDIR=$(BASEDIR))
+.PHONY: lib
+lib:
+	@cd lib && $(MAKE) -s BASEDIR=$(BASEDIR)
 
-clean: FORCE
-	@(cd lib && $(MAKE) BASEDIR=$(BASEDIR) clean)
-	@for file in `find interactive tests -name Makefile`; do \
+.PHONY: clean
+clean:
+	@cd lib && $(MAKE) BASEDIR=$(BASEDIR) clean
+	@for file in `$(FIND) interactive tests -name Makefile`; do \
 	  (cd `dirname $$file` && $(MAKE) BASEDIR=$(BASEDIR) clean); \
 	done
 
-report: FORCE
+.PHONY: report
+report:
 	@if [ ! -f _log ]; then echo "No '_log' file."; exit 1; fi
-	@echo ''
-	@echo 'Summary:'
-	@echo '  ' `grep 'passed$$' _log | wc -l` 'test(s) passed'
-	@echo '  ' `grep 'failed$$' _log | wc -l` 'test(s) failed'
-	@echo '  ' `grep '^Error' _log | wc -l` 'compilation error(s)'
-	@echo '  ' `grep '^Warning' _log | wc -l` 'compilation warning(s)'
-	@echo '  ' `grep '^make\[2\]: ' _log | wc -l` 'makefile error(s)'
+	@awk -f makefiles/summarize.awk <_log
 
-empty: FORCE
-
-FORCE:
+.PHONY: empty
+empty:
diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -1,4 +1,14 @@
-# $Id: Makefile.several 12959 2012-09-27 13:12:51Z maranget $
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
 
 CC=$(NATIVECC) $(NATIVECCCOMPOPTS)
 FC=$(FORTAN_COMPILER)
@@ -8,54 +18,89 @@ CMA_FILES=$(LIBRARIES:=.cma)
 CMXA_FILES=$(LIBRARIES:=.cmxa)
 O_FILES=$(C_FILES:=.o)
 
-CUSTOM_FLAG=`if [ -z "$(C_FILES)" ]; then true; else echo '-custom'; fi`
+CUSTOM_FLAG=`if [ -n "$(C_FILES)" ]; then echo '-custom'; fi`
 ADD_CFLAGS+=$(CUSTOM_FLAG)
-FORTRAN_LIB=`if [ -z "$(F_FILES)" ]; then true; else echo '$(FORTRAN_LIBRARY)'; fi`
+MYRUNTIME=`if [ -z "$(C_FILES)" ]; then echo '$(OCAMLRUN)'; fi`
+FORTRAN_LIB=`if [ -n "$(F_FILES)" ]; then echo '$(FORTRAN_LIBRARY)'; fi`
 ADD_CFLAGS+=$(FORTRAN_LIB)
 ADD_OPTFLAGS+=$(FORTRAN_LIB)
-ADD_COMPFLAGS+=-nojoin
 
+.PHONY: check
 check:
-	@if [ -n "$(FORTRAN_COMPILER)" -o -z "$(F_FILES)" ]; then $(MAKE) run-all; fi
+	@if [ -n "$(FORTRAN_COMPILER)" -o -z "$(F_FILES)" ]; then \
+	  $(SET_LD_PATH) $(MAKE) run-all; \
+	fi
 
+.PHONY: run-all
 run-all:
 	@for file in $(C_FILES); do \
-	  $(CC) -c -I$(PREFIX)/lib/ocaml/jocaml $$file.c; \
+	  $(CC) -c -I$(PREFIX)/lib/ocaml/caml $$file.c; \
 	done;
 	@for file in $(F_FILES); do \
-	  $(FORTRAN_COMPILER) -c -I$(PREFIX)/lib/ocaml/jocaml $$file.f; \
+	  $(FORTRAN_COMPILER) -c -I$(PREFIX)/lib/ocaml/caml $$file.f; \
 	done;
 	@for file in *.ml; do \
+	  if [ -f `basename $$file ml`precheck ]; then \
+	    CANKILL=$(CANKILL) sh `basename $$file ml`precheck || continue; \
+	  fi; \
 	  printf " ... testing '$$file':"; \
-	  $(MAKE) run-file DESC=jocamlc COMP='$(OCAMLC)' COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_CFLAGS) $(O_FILES) -w a $(CMA_FILES) -I $(BASEDIR)/lib $(CMO_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS) && \
-	  if [ -z "$(BYTECODE_ONLY)" ]; then \
-	    $(MAKE) run-file DESC=jocamlopt COMP=$(PREFIX)/bin/jocamlopt COMPFLAGS='$(ADD_COMPFLAGS) $(ADD_OPTFLAGS) $(O_FILES) -w a $(CMXA_FILES) -I $(BASEDIR)/lib $(CMX_FILES)' FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS); \
-	  fi && \
-	  if [ ! -z $(UNSAFE) ]; then \
-	    $(MAKE) run-file DESC=jocamlc-unsafe COMP=$(PREFIX)/bin/jocamlc COMPFLAGS='-w a -unsafe -I $(BASEDIR)/lib $(CMO_FILES)' FILE=$$file && \
-	    if [ -z "$(BYTECODE_ONLY)" ]; then \
-	      $(MAKE) run-file DESC=jocamlopt-unsafe COMP=$(PREFIX)/bin/jocamlopt COMPFLAGS='-w a -unsafe -I $(BASEDIR)/lib $(CMX_FILES)' FILE=$$file; \
-	    fi; \
-	  fi && \
-	  echo " => passed"; \
-	done;
+	  $(MAKE) run-file DESC=ocamlc COMP='$(OCAMLC)' \
+	          RUNTIME='$(MYRUNTIME)' \
+	          COMPFLAGS='-w a $(ADD_COMPFLAGS) $(ADD_CFLAGS) $(O_FILES) \
+	                     $(CMA_FILES) -I $(OTOPDIR)/testsuite/lib \
+	                     $(CMO_FILES)' \
+	          FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS) \
+	  && \
+	  if $(BYTECODE_ONLY); then : ; else \
+	    $(MAKE) run-file DESC=ocamlopt COMP='$(OCAMLOPT)' \
+	            RUNTIME= \
+	            COMPFLAGS='-w a $(ADD_COMPFLAGS) $(ADD_OPTFLAGS) \
+		               $(O_FILES) $(CMXA_FILES) \
+			       -I $(OTOPDIR)/testsuite/lib $(CMX_FILES)' \
+	            FILE=$$file PROGRAM_ARGS=$(PROGRAM_ARGS); \
+	  fi \
+	  && \
+	  if [ -n "$(UNSAFE)" ]; then \
+	    $(MAKE) run-file DESC=ocamlc-unsafe COMP='$(OCAMLC)' \
+	            RUNTIME='$(MYRUNTIME)' \
+	            COMPFLAGS='-w a -unsafe $(ADD_COMPFLAGS) $(ADD_CFLAGS) \
+	                       $(O_FILES) $(CMA_FILES) \
+	                       -I $(OTOPDIR)/testsuite/lib $(CMO_FILES)' \
+	            FILE=$$file \
+	    && \
+	    if $(BYTECODE_ONLY); then : ; else \
+	      $(MAKE) run-file DESC=ocamlopt-unsafe COMP='$(OCAMLOPT)' \
+	              RUNTIME= \
+	              COMPFLAGS='-w a -unsafe $(ADD_COMPFLAGS) $(ADD_OPTFLAGS)\
+		                 $(O_FILES) $(CMXA_FILES) \
+	                         -I $(OTOPDIR)/testsuite/lib $(CMX_FILES)' \
+	              FILE=$$file; \
+	       fi; \
+	     fi \
+	  && echo " => passed" || echo " => failed"; \
+	done
 
+.PHONY: run-file
 run-file:
 	@printf " $(DESC)"
 	@rm -f program program.exe
-	@$(COMP) $(COMPFLAGS) $(FILE) -o program
-	@if [ -f `basename $(FILE) ml`runner ]; then \
-	  sh `basename $(FILE) ml`runner; \
+	@$(COMP) $(COMPFLAGS) $(FILE) -o program$(EXE)
+	@F="`basename $(FILE) .ml`"; \
+	if [ -f $$F.runner ]; then \
+	  RUNTIME="$(RUNTIME)" sh $$F.runner; \
 	else \
-	  ./program $(PROGRAM_ARGS) > `basename $(FILE) ml`result; \
-	fi || (echo " => failed" && exit 1)
-	@if [ -f `basename $(FILE) ml`checker ]; then \
-	  sh `basename $(FILE) ml`checker; \
+	  $(RUNTIME) ./program$(EXE) $(PROGRAM_ARGS) >$$F.result; \
+	fi \
+	&& \
+	if [ -f $$F.checker ]; then \
+	  DIFF="$(DIFF)" SORT="$(SORT)" sh $$F.checker; \
 	else \
-	  $(DIFF) `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null; \
-	fi || (echo " => failed" && exit 1)
+	  $(DIFF) $$F.reference $$F.result >/dev/null; \
+	fi
 
+.PHONY: promote
 promote: defaultpromote
 
+.PHONY: clean
 clean: defaultclean
-	@rm -f *.result ./program program.exe
+	@rm -f *.result program program.exe
diff --git a/testsuite/makefiles/Makefile.toplevel b/testsuite/makefiles/Makefile.toplevel
--- a/testsuite/makefiles/Makefile.toplevel
+++ b/testsuite/makefiles/Makefile.toplevel
@@ -1,15 +1,28 @@
-# $Id: Makefile.toplevel 12858 2012-08-10 14:45:51Z maranget $
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
 
 default:
 	@for file in *.ml; do \
-	  $(OCAML) < $$file 2>&1 | grep -v '^        JoCaml version' > $$file.result; \
+	  $(OCAML) $(TOPFLAGS) <$$file 2>&1 \
+	    | grep -v '^        OCaml version' > $$file.result; \
 	  if [ -f $$file.principal.reference ]; then \
-	    $(OCAML) -principal < $$file 2>&1 | grep -v '^        JoCaml version' > $$file.principal.result; \
+	    $(OCAML) $(TOPFLAGS) -principal <$$file 2>&1 \
+	      | grep -v '^        OCaml version' > $$file.principal.result; \
 	  fi; \
 	done
 	@for file in *.reference; do \
 	  printf " ... testing '$$file':"; \
-	  $(DIFF) $$file `basename $$file reference`result || (echo " => failed" && exit 1) && echo " => passed"; \
+	  $(DIFF) $$file `basename $$file reference`result >/dev/null \
+          && echo " => passed" || echo " => failed"; \
 	done
 
 promote: defaultpromote
diff --git a/testsuite/tests/backtrace/Makefile b/testsuite/tests/backtrace/Makefile
--- a/testsuite/tests/backtrace/Makefile
+++ b/testsuite/tests/backtrace/Makefile
@@ -1,19 +1,38 @@
-BASEDIR=../..
-EXECNAME=./program
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
 
+BASEDIR=../..
+EXECNAME=program$(EXE)
+
+.PHONY: run-all
 run-all:
 	@for file in *.ml; do \
+	  rm -f program program.exe; \
 	  $(OCAMLC) -g -o $(EXECNAME) $$file; \
 	  for arg in a b c d ''; do \
-	    printf " ... testing '$$file' (with argument '$$arg'):"; \
-	    OCAMLRUNPARAM=b=1 $(EXECNAME) $$arg > `basename $$file ml`$$arg.result 2>&1; \
-	    $(DIFF) `basename $$file ml`$$arg.reference `basename $$file ml`$$arg.result > /dev/null && echo " => passed" || (echo " => failed" && exit 1); \
+	    printf " ... testing '$$file' with argument '$$arg':"; \
+	    F="`basename $$file .ml`"; \
+	    (OCAMLRUNPARAM=b=1 $(OCAMLRUN) $(EXECNAME) $$arg || true) \
+	         >$$F.$$arg.result 2>&1; \
+	    $(DIFF) $$F.$$arg.reference $$F.$$arg.result >/dev/null \
+	    && echo " => passed" || echo " => failed"; \
 	  done; \
 	done
 
+.PHONY: promote
 promote: defaultpromote
 
+.PHONY: clean
 clean: defaultclean
-	@rm -f *.result $(EXECNAME)
+	@rm -f *.result program program.exe
 
 include $(BASEDIR)/makefiles/Makefile.common
diff --git a/testsuite/tests/callback/Makefile b/testsuite/tests/callback/Makefile
--- a/testsuite/tests/callback/Makefile
+++ b/testsuite/tests/callback/Makefile
@@ -1,32 +1,57 @@
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
+
 BASEDIR=../..
 
-CC=$(NATIVECC) -I $(TOPDIR)/byterun
+CC=$(NATIVECC) -I $(CTOPDIR)/byterun
+COMPFLAGS=-I $(OTOPDIR)/otherlibs/unix
+LD_PATH=$(TOPDIR)/otherlibs/unix
 
-default: run-byte run-opt
+.PHONY: default
+default:
+	@case " $(OTHERLIBRARIES) " in \
+	  *' unix '*) $(SET_LD_PATH) $(MAKE) run-byte run-opt;; \
+	esac
 
+.PHONY: common
 common:
 	@$(CC) -c callbackprim.c
 
+.PHONY: run-byte
 run-byte: common
 	@printf " ... testing 'bytecode':"
-	@$(OCAMLC) -c tcallback.ml
-	@$(OCAMLC) -o ./program -custom unix.cma callbackprim.$(O) tcallback.cmo
-	@./program > bytecode.result
-	@$(DIFF) reference bytecode.result || (echo " => failed" && exit 1) 
-	@echo " => passed"
+	@$(OCAMLC) $(COMPFLAGS) -c tcallback.ml
+	@$(OCAMLC) $(COMPFLAGS) -o ./program -custom unix.cma \
+	           callbackprim.$(O) tcallback.cmo
+	@./program >bytecode.result
+	@$(DIFF) reference bytecode.result \
+	&& echo " => passed" || echo " => failed"
 
+.PHONY: run-opt
 run-opt: common
-	@if [ -z "$(BYTECODE_ONLY)" ]; then \
+	@if $(BYTECODE_ONLY); then : ; else \
 	  printf " ... testing 'native':"; \
-	  $(OCAMLOPT) -c tcallback.ml; \
-	  $(OCAMLOPT) -o ./program unix.cmxa callbackprim.$(O) tcallback.cmx; \
-	  ./program > native.result; \
-	  $(DIFF) reference native.result || (echo " => failed" && exit 1); \
-	  echo " => passed"; \
+	  $(OCAMLOPT) $(COMPFLAGS) -c tcallback.ml; \
+	  $(OCAMLOPT) $(COMPFLAGS) -o ./program unix.cmxa callbackprim.$(O) \
+	              tcallback.cmx; \
+	  ./program >native.result; \
+	  $(DIFF) reference native.result \
+	  && echo " => passed" || echo " => failed"; \
 	fi
-	
+
+.PHONY: promote
 promote: defaultpromote
 
+.PHONY: clean
 clean: defaultclean
 	@rm -f *.result ./program
 
diff --git a/testsuite/tests/lib-dynlink-bytecode/Makefile b/testsuite/tests/lib-dynlink-bytecode/Makefile
--- a/testsuite/tests/lib-dynlink-bytecode/Makefile
+++ b/testsuite/tests/lib-dynlink-bytecode/Makefile
@@ -1,41 +1,71 @@
+#########################################################################
+#                                                                       #
+#                                 OCaml                                 #
+#                                                                       #
+#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
+#                                                                       #
+#   Copyright 2010 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
+
 BASEDIR=../..
 
-default: compile run
+COMPFLAGS=-I $(OTOPDIR)/otherlibs/dynlink
+LD_PATH=.:$(TOPDIR)/otherlibs/dynlink
 
-compile:
+.PHONY: default
+default:
+	@$(SET_LD_PATH) $(MAKE) compile run
+
+.PHONY: compile
+compile: caml
 	@$(OCAMLC) -c registry.ml
 	@for file in stub*.c; do \
-	  $(OCAMLC) -c $$file; \
-	  $(OCAMLMKLIB) -o `echo $$file | sed -e 's/stub/plug/' | sed -e 's/\.c//'` `basename $$file c`o; \
+	  $(OCAMLC) -ccopt -I -ccopt . -c $$file; \
+	  $(OCAMLMKLIB) -o `echo $$file | sed -e 's/stub/plug/' -e 's/\.c//'` \
+	                `basename $$file c`$(O); \
 	done
 	@for file in plug*.ml; do \
 	  $(OCAMLC) -c $$file; \
 	  $(OCAMLMKLIB) -o `basename $$file .ml` `basename $$file ml`cmo; \
 	done
 	@$(OCAMLC) -c main.ml
+	@rm -f main static custom custom.exe
 	@$(OCAMLC) -o main dynlink.cma registry.cmo main.cmo
-	@$(OCAMLC) -o static -linkall registry.cmo plug1.cma plug2.cma -use-runtime $(PREFIX)/bin/jocamlrun
-	@$(OCAMLC) -o custom -custom -linkall registry.cmo plug2.cma plug1.cma -I .
+	@$(OCAMLC) -o static -linkall registry.cmo plug1.cma plug2.cma \
+	           -use-runtime $(OTOPDIR)/boot/ocamlrun$(EXE)
+	@$(OCAMLC) -o custom$(EXE) -custom -linkall registry.cmo plug2.cma \
+	           plug1.cma -I .
 
+caml:
+	@mkdir -p caml || :
+	@cp -f $(TOPDIR)/byterun/*.h caml/
+
+.PHONY: run
 run:
 	@printf " ... testing 'main'"
-	@export LD_LIBRARY_PATH=`pwd` && ./main plug1.cma plug2.cma > main.result
-	@$(DIFF) main.reference main.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@$(OCAMLRUN) ./main plug1.cma plug2.cma >main.result
+	@$(DIFF) main.reference main.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
 
 	@printf " ... testing 'static'"
-	@export LD_LIBRARY_PATH=`pwd` && ./static > static.result
-	@$(DIFF) static.reference static.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
+	@$(OCAMLRUN) ./static >static.result
+	@$(DIFF) static.reference static.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
 
 	@printf " ... testing 'custom'"
-	@export LD_LIBRARY_PATH=`pwd` && ./custom > custom.result
-	@$(DIFF) custom.reference custom.result > /dev/null || (echo " => failed" && exit 1)
-	@echo " => passed"
-	
+	@./custom$(EXE) >custom.result
+	@$(DIFF) custom.reference custom.result >/dev/null \
+	&& echo " => passed" || echo " => failed"
+
+.PHONY: promote
 promote: defaultpromote
 
+.PHONY: clean
 clean: defaultclean
-	@rm -f ./main ./static ./custom *.result marshal.data
+	@rm -f main static custom custom.exe *.result marshal.data
+	@rm -rf caml
 
 include $(BASEDIR)/makefiles/Makefile.common
